import { createEmitter, createLight, type NewFilePreset } from './types'

// Nuclear mushroom cloud. Critical design constraints learned from the shader:
// - The mushroom cap and stem are NOT separate emitters at different heights —
//   they emerge from the fluid dynamics (toroidal circulation) driven by a
//   single ground-level detonation with high mushroomStrength + implosionStrength.
// - Extra sources should be at or near ground level with staggered startTimes.
// - Crown rolls are small sources that fire after the cap has risen, placed
//   at the approximate altitude the cap reaches — but only to add density
//   texture, not to create a second blast.
export const nuclearDetonationPreset: NewFilePreset = {
  id: 'nuclear-detonation',
  label: 'Nuclear Detonation',
  description: 'Staged fireball, dense stem column, and toroidal mushroom cap.',
  emitters: [
    // The primary detonation — ground zero. Very high impulse, strong toroidal
    // circulation, high implosion to collapse the lower orb and feed the stem.
    createEmitter('Ground Zero', {
      position: [0.5, 0.075, 0.5],
      radius: 0.1,
      startTime: 0,
      smokeLeadTime: 0.01,
      blastDuration: 0.16,
      plumeDuration: 8.5,
      densityYield: 0.38,
      heatYield: 42,
      fuelYield: 10.5,
      reactionYield: 6.0,
      radialImpulse: 155,
      liftDirection: [0, 1, 0],
      liftImpulse: 62,
      heatPatchiness: 0.9,
      patchScale: 55,
      coreHeat: 9.5,
      coreLift: 48,
      turbulence: 15,
      crumbleStrength: 11,
      implosionStrength: 22,
      expansionRate: 1.3,
      sustain: 0.55,
      mushroomStrength: 6.5,
      smokeEntrainment: 5.2,
      seed: 401,
    }),
    // Secondary ground flash — slightly offset to break symmetry, fires 0.1s later
    createEmitter('Ground Flash B', {
      position: [0.492, 0.065, 0.507],
      radius: 0.072,
      startTime: 0.1,
      smokeLeadTime: 0.005,
      blastDuration: 0.14,
      plumeDuration: 6.8,
      densityYield: 0.32,
      heatYield: 32,
      fuelYield: 7.8,
      reactionYield: 4.5,
      radialImpulse: 115,
      liftDirection: [0.02, 1, -0.015],
      liftImpulse: 48,
      heatPatchiness: 0.88,
      patchScale: 48,
      coreHeat: 7.2,
      coreLift: 36,
      turbulence: 13,
      crumbleStrength: 9,
      implosionStrength: 16,
      expansionRate: 1.1,
      sustain: 0.44,
      mushroomStrength: 5.0,
      smokeEntrainment: 4.0,
      seed: 409,
    }),
    // Toroidal smoke cap — fires at ground level but has a near-zero radialImpulse
    // and very high mushroomStrength. The toroidal circulation from the primary
    // detonation carries this material upward and spreads it into the cap shape.
    // It is still a ground-level source — NOT placed at mushroom height.
    createEmitter('Cap Smoke', {
      position: [0.5, 0.085, 0.5],
      radius: 0.12,
      startTime: 0.55,
      smokeLeadTime: 0,
      blastDuration: 0.45,
      plumeDuration: 7.5,
      densityYield: 1.55,
      heatYield: 12,
      fuelYield: 3.5,
      reactionYield: 1.8,
      radialImpulse: 45,
      liftDirection: [0, 1, 0],
      liftImpulse: 30,
      heatPatchiness: 0.92,
      patchScale: 42,
      coreHeat: 2.5,
      coreLift: 16,
      turbulence: 12,
      crumbleStrength: 8,
      implosionStrength: 1.5,
      expansionRate: 1.18,
      sustain: 0.38,
      mushroomStrength: 7.2,
      smokeEntrainment: 2.0,
      seed: 421,
    }),
    // Four asymmetric crown rolls — small, at slightly different timings and
    // offsets from center to create a non-uniform ragged top.
    createEmitter('Crown — Left', {
      position: [0.43, 0.078, 0.515],
      radius: 0.056,
      startTime: 0.85,
      smokeLeadTime: 0,
      blastDuration: 0.35,
      plumeDuration: 5.5,
      densityYield: 1.0,
      heatYield: 7.0,
      fuelYield: 2.0,
      reactionYield: 1.1,
      radialImpulse: 38,
      liftDirection: [-0.55, 0.78, 0.13],
      liftImpulse: 20,
      heatPatchiness: 0.93,
      patchScale: 46,
      coreHeat: 1.0,
      coreLift: 7,
      turbulence: 11,
      crumbleStrength: 7,
      implosionStrength: 0.5,
      expansionRate: 0.82,
      sustain: 0.18,
      mushroomStrength: 4.5,
      smokeEntrainment: 1.2,
      seed: 433,
    }),
    createEmitter('Crown — Right', {
      position: [0.578, 0.072, 0.476],
      radius: 0.058,
      startTime: 0.92,
      smokeLeadTime: 0,
      blastDuration: 0.33,
      plumeDuration: 5.2,
      densityYield: 0.95,
      heatYield: 6.5,
      fuelYield: 1.9,
      reactionYield: 1.0,
      radialImpulse: 40,
      liftDirection: [0.56, 0.76, -0.12],
      liftImpulse: 21,
      heatPatchiness: 0.92,
      patchScale: 48,
      coreHeat: 0.95,
      coreLift: 7,
      turbulence: 11,
      crumbleStrength: 7,
      implosionStrength: 0.5,
      expansionRate: 0.84,
      sustain: 0.16,
      mushroomStrength: 4.2,
      smokeEntrainment: 1.1,
      seed: 439,
    }),
    createEmitter('Crown — Front', {
      position: [0.505, 0.07, 0.43],
      radius: 0.054,
      startTime: 0.89,
      smokeLeadTime: 0,
      blastDuration: 0.32,
      plumeDuration: 5.0,
      densityYield: 0.9,
      heatYield: 6.2,
      fuelYield: 1.8,
      reactionYield: 0.95,
      radialImpulse: 36,
      liftDirection: [0.07, 0.76, -0.62],
      liftImpulse: 19,
      heatPatchiness: 0.93,
      patchScale: 47,
      coreHeat: 0.9,
      coreLift: 6,
      turbulence: 10,
      crumbleStrength: 6.5,
      implosionStrength: 0.4,
      expansionRate: 0.8,
      sustain: 0.15,
      mushroomStrength: 4.0,
      smokeEntrainment: 1.1,
      seed: 443,
    }),
    createEmitter('Crown — Back', {
      position: [0.494, 0.076, 0.574],
      radius: 0.056,
      startTime: 0.96,
      smokeLeadTime: 0,
      blastDuration: 0.32,
      plumeDuration: 4.8,
      densityYield: 0.92,
      heatYield: 6.0,
      fuelYield: 1.75,
      reactionYield: 0.92,
      radialImpulse: 37,
      liftDirection: [-0.07, 0.77, 0.62],
      liftImpulse: 19,
      heatPatchiness: 0.92,
      patchScale: 49,
      coreHeat: 0.9,
      coreLift: 6,
      turbulence: 10,
      crumbleStrength: 6.5,
      implosionStrength: 0.4,
      expansionRate: 0.82,
      sustain: 0.15,
      mushroomStrength: 4.0,
      smokeEntrainment: 1.0,
      seed: 449,
    }),
  ],
  lights: [
    createLight('High Sun', {
      lightType: 'directional',
      dirX: -0.42, dirY: 0.86, dirZ: 0.28,
      posX: 0.5, posY: 0.85, posZ: 0.5,
      intensity: 2.25,
      colorR: 1.0, colorG: 0.9, colorB: 0.78,
    }),
  ],
  runtimeParams: {
    wind: [0.012, 0, -0.008],
    windStrength: 0.06,
    buoyancy: 8.8,
    vorticityStrength: 6.0,
  },
  renderOutput: {
    stepCount: 448,
    scatteringForward: 0.38,
    scatteringBack: -0.22,
  },
}
