import { createEmitter, createLight, type NewFilePreset } from './types'

// Oil well fires are notably different from explosions:
// - extremely dense, black smoke with a narrow hot core that never fully cools
// - flame sits low and tight, smoke billows upward in a thick rolling column
// - strong crosswind separates the sooty cap from the flame base
// - the column leans heavily downwind and flattens into a dark anvil at altitude
export const oilWellFirePreset: NewFilePreset = {
  id: 'oil-well-fire',
  label: 'Oil Well Fire',
  description: 'Dense sooty column with a sustained low flame and wind-sheared rolling top.',
  emitters: [
    // Tight, intensely hot flame base — relatively small radius, very high heat
    createEmitter('Flame Base', {
      position: [0.5, 0.055, 0.5],
      radius: 0.044,
      startTime: 0,
      smokeLeadTime: 0,
      blastDuration: 20,
      plumeDuration: 40,
      densityYield: 0.42,
      heatYield: 14.5,
      fuelYield: 12.8,
      reactionYield: 2.2,
      radialImpulse: 3.2,
      liftDirection: [0, 1, 0],
      liftImpulse: 8.5,
      heatPatchiness: 0.22,
      patchScale: 8,
      coreHeat: 6.8,
      coreLift: 12,
      turbulence: 4.2,
      crumbleStrength: 2.8,
      implosionStrength: 0,
      expansionRate: 0.22,
      sustain: 2.4,
      mushroomStrength: 0.08,
      smokeEntrainment: 0.6,
      seed: 811,
    }),
    // The main sooty smoke column — extremely dense, wide, slow-rising
    createEmitter('Smoke Pillar', {
      position: [0.5, 0.1, 0.5],
      radius: 0.085,
      startTime: 0.6,
      smokeLeadTime: 0,
      blastDuration: 22,
      plumeDuration: 40,
      densityYield: 3.8,
      heatYield: 3.2,
      fuelYield: 2.1,
      reactionYield: 0.5,
      radialImpulse: 1.8,
      liftDirection: [0.06, 1, -0.04],
      liftImpulse: 6.2,
      heatPatchiness: 0.72,
      patchScale: 24,
      coreHeat: 1.4,
      coreLift: 5.5,
      turbulence: 3.5,
      crumbleStrength: 2.4,
      implosionStrength: 0,
      expansionRate: 0.62,
      sustain: 1.8,
      mushroomStrength: 0.12,
      smokeEntrainment: 1.4,
      seed: 827,
    }),
    // The billowing upper cap where wind shears the top and creates rolling lobes
    createEmitter('Rolling Cap', {
      position: [0.5, 0.24, 0.5],
      radius: 0.105,
      startTime: 2.2,
      smokeLeadTime: 0,
      blastDuration: 24,
      plumeDuration: 40,
      densityYield: 2.6,
      heatYield: 1.2,
      fuelYield: 0.6,
      reactionYield: 0.15,
      radialImpulse: 4.5,
      liftDirection: [0.12, 0.88, -0.08],
      liftImpulse: 3.8,
      heatPatchiness: 0.88,
      patchScale: 36,
      coreHeat: 0.4,
      coreLift: 2.2,
      turbulence: 6.5,
      crumbleStrength: 4.2,
      implosionStrength: 0,
      expansionRate: 0.92,
      sustain: 1.2,
      mushroomStrength: 0.3,
      smokeEntrainment: 2.4,
      seed: 839,
    }),
  ],
  lights: [
    createLight('Harsh Noon Sun', {
      lightType: 'directional',
      dirX: -0.18, dirY: 0.96, dirZ: 0.22,
      posX: 0.5, posY: 0.9, posZ: 0.5,
      intensity: 2.8,
      colorR: 1.0, colorG: 0.97, colorB: 0.92,
    }),
  ],
  runtimeParams: {
    wind: [0.085, 0, -0.04],
    windStrength: 0.58,
    buoyancy: 5.2,
    vorticityStrength: 2.8,
  },
  renderOutput: {
    stepCount: 360,
    scatteringForward: 0.18,
    scatteringBack: -0.06,
  },
}
