import { createScalarEmitter, createVelocityEmitter, createIgniterEmitter, createLight, type NewFilePreset } from './types'

export const volcanicEruptionPreset: NewFilePreset = {
  id: 'volcanic-eruption',
  label: 'Volcanic Eruption',
  description: 'Sustained ash column with intermittent hot pulses and a delayed base surge.',
  emitters: [
    createScalarEmitter('Dense Vent Ash', {
      positionX: 0.5, positionY: 0.055, positionZ: 0.5,
      radius: 0.045,
      startTime: 0,
      duration: 9999,
      densityRate: 2.5,
      heatRate: 7.5,
      fuelRate: 0.6,
      noiseScale: 9,
      noiseMix: 0.42,
      seed: 501,
    }),
    createVelocityEmitter('Vent Jet', {
      positionX: 0.5, positionY: 0.058, positionZ: 0.5,
      radius: 0.038,
      startTime: 0,
      duration: 9999,
      mode: 'directional',
      speed: 34,
      directionX: 0.02, directionY: 1, directionZ: -0.015,
      falloff: 0.7,
      seed: 509,
    }),
    createScalarEmitter('Hot Pulse', {
      positionX: 0.5, positionY: 0.075, positionZ: 0.5,
      radius: 0.06,
      startTime: 1.2,
      duration: 1.5,
      densityRate: 2.2,
      heatRate: 9.0,
      fuelRate: 0.2,
      noiseScale: 16,
      noiseMix: 0.7,
      seed: 519,
    }),
    createScalarEmitter('Base Surge', {
      positionX: 0.5, positionY: 0.05, positionZ: 0.5,
      radius: 0.14,
      startTime: 3.4,
      duration: 5.0,
      densityRate: 2.0,
      heatRate: 0.5,
      fuelRate: 0,
      noiseScale: 24,
      noiseMix: 0.75,
      seed: 523,
    }),
    createVelocityEmitter('Surge Spread', {
      positionX: 0.5, positionY: 0.052, positionZ: 0.5,
      radius: 0.14,
      startTime: 3.35,
      duration: 4.0,
      mode: 'radial',
      speed: 14,
      directionX: 0, directionY: 0, directionZ: 0,
      falloff: 0.4,
      seed: 541,
    }),
    createIgniterEmitter('Ignition', {
      positionX: 0.5, positionY: 0.06, positionZ: 0.5,
      radius: 0.05,
      startTime: 0,
      duration: 0.5,
      intensity: 0.8,
      seed: 557,
    }),
  ],
  lights: [
    createLight('Tropical Sun', {
      lightType: 'directional',
      dirX: -0.22, dirY: 0.94, dirZ: 0.26,
      posX: 0.5, posY: 0.9, posZ: 0.5,
      intensity: 2.4,
      colorR: 1.0, colorG: 0.98, colorB: 0.88,
    }),
  ],
  runtimeParams: {
    wind: [0.042, 0, -0.022],
    windStrength: 0.3,
    gravity: [0, -1, 0],
    gravityStrength: 0.45,
    buoyancy: 5.8,
    vorticityStrength: 4.1,
    worldSize: 200,
  },
  renderOutput: {
    stepCount: 440,
    scatteringForward: 0.24,
    scatteringBack: -0.1,
  },
}
