import { createBurstEmitter, createScalarEmitter, createVelocityEmitter, createLight, type NewFilePreset } from './types'

export const volcanicEruptionPreset: NewFilePreset = {
  id: 'volcanic-eruption',
  label: 'Volcanic Eruption',
  description: 'Sustained vent jet with pulsed pyroclasts, ash-column rollup, and a late base surge.',
  emitters: [
    createScalarEmitter('Dense Vent Ash', {
      positionX: 0.5, positionY: 0.055, positionZ: 0.5,
      radius: 0.04,
      startTime: 0,
      duration: 9999,
      densityRate: 2.2,
      heatRate: 5.8,
      fuelRate: 0.18,
      noiseScale: 11,
      noiseMix: 0.58,
      seed: 501,
    }),
    // worldSize=220 → dx=1.72, speedLimit≈46. Keep all speeds under 44.
    createVelocityEmitter('Column Jet', {
      positionX: 0.5, positionY: 0.07, positionZ: 0.5,
      radius: 0.048,
      startTime: 0,
      duration: 9999,
      mode: 'directional',
      speed: 42,
      directionX: 0.02, directionY: 1, directionZ: -0.015,
      falloff: 0.84,
      tightness: 0.62,
      seed: 509,
    }),
    createBurstEmitter('Hot Pyroclast Pulse A', {
      positionX: 0.5, positionY: 0.095, positionZ: 0.5,
      radius: 0.082,
      startTime: 1.1,
      duration: 0.32,
      densityAmount: 0.55,
      heatAmount: 1.45,
      fuelAmount: 0.65,
      reactionAmount: 0.55,
      expansionSpeed: 38,
      liftSpeed: 42,
      turbulenceSpeed: 30,
      falloff: 0.44,
      noiseScale: 22,
      noiseMix: 0.82,
      seed: 519,
    }),
    createBurstEmitter('Hot Pyroclast Pulse B', {
      positionX: 0.49, positionY: 0.1, positionZ: 0.51,
      radius: 0.092,
      startTime: 3.0,
      duration: 0.38,
      densityAmount: 0.72,
      heatAmount: 1.62,
      fuelAmount: 0.72,
      reactionAmount: 0.58,
      expansionSpeed: 42,
      liftSpeed: 44,
      turbulenceSpeed: 34,
      falloff: 0.42,
      noiseScale: 20,
      noiseMix: 0.84,
      seed: 523,
    }),
    createBurstEmitter('Base Surge Collapse', {
      positionX: 0.5, positionY: 0.052, positionZ: 0.5,
      radius: 0.18,
      startTime: 3.8,
      duration: 1.4,
      densityAmount: 1.3,
      heatAmount: 0.16,
      fuelAmount: 0,
      reactionAmount: 0,
      expansionSpeed: 28,
      liftSpeed: -2,
      turbulenceSpeed: 22,
      falloff: 0.62,
      noiseScale: 16,
      noiseMix: 0.78,
      seed: 541,
    }),
    createVelocityEmitter('Ash Column Roll', {
      positionX: 0.5, positionY: 0.3, positionZ: 0.5,
      radius: 0.2,
      startTime: 1.2,
      duration: 9999,
      mode: 'turbulent',
      speed: 20,
      directionX: 0, directionY: 1, directionZ: 0,
      falloff: 0.72,
      tightness: 0.07,
      seed: 557,
    }),
  ],
  lights: [
    createLight('Tropical Sun', {
      lightType: 'directional',
      dirX: -0.22, dirY: 0.94, dirZ: 0.26,
      posX: 0.5, posY: 0.9, posZ: 0.5,
      intensity: 2.4,
      colorR: 1.0, colorG: 0.98, colorB: 0.88,
    }),
  ],
  runtimeParams: {
    wind: [0.042, 0, -0.022],
    windStrength: 0.32,
    gravity: [0, -1, 0],
    gravityStrength: 0.42,
    buoyancy: 9.8,
    vorticityStrength: 7.5,
    vorticityConstantMask: 0.75,
    vorticityVelocityMask: 0.75,
    vorticityHeatMask: 1.15,
    vorticityDensityMask: 0.85,
    worldSize: 220,
  },
  renderOutput: {
    stepCount: 520,
    scatteringForward: 0.22,
    scatteringBack: -0.08,
  },
}
