import { createEmitter, createLight, type NewFilePreset } from './types'

export const nuclearDetonationPreset: NewFilePreset = {
  id: 'nuclear-detonation',
  label: 'Nuclear Detonation',
  description: 'Staged fireball, dense stem, and rolling mushroom cap.',
  emitters: [
    // Ground zero — the hard initial flash that births the fireball
    createEmitter('Ground Flash', {
      position: [0.5, 0.07, 0.5],
      radius: 0.092,
      startTime: 0,
      smokeLeadTime: 0.01,
      blastDuration: 0.18,
      plumeDuration: 7.2,
      densityYield: 0.38,
      heatYield: 38,
      fuelYield: 9.2,
      reactionYield: 5.8,
      radialImpulse: 148,
      liftDirection: [0, 1, 0],
      liftImpulse: 58,
      heatPatchiness: 0.88,
      patchScale: 52,
      coreHeat: 8.6,
      coreLift: 42,
      turbulence: 14,
      crumbleStrength: 10,
      implosionStrength: 18,
      expansionRate: 1.22,
      sustain: 0.48,
      mushroomStrength: 3.4,
      smokeEntrainment: 4.2,
      seed: 401,
    }),
    // Dense, narrow stem that feeds the cap from below
    createEmitter('Stem Column', {
      position: [0.5, 0.14, 0.5],
      radius: 0.052,
      startTime: 0.22,
      smokeLeadTime: 0.02,
      blastDuration: 0.32,
      plumeDuration: 9.5,
      densityYield: 1.8,
      heatYield: 22,
      fuelYield: 6.2,
      reactionYield: 3.2,
      radialImpulse: 18,
      liftDirection: [0.01, 1, -0.008],
      liftImpulse: 76,
      heatPatchiness: 0.68,
      patchScale: 28,
      coreHeat: 5.4,
      coreLift: 62,
      turbulence: 5,
      crumbleStrength: 3.5,
      implosionStrength: 6,
      expansionRate: 0.52,
      sustain: 0.94,
      mushroomStrength: 1.8,
      smokeEntrainment: 6.8,
      seed: 409,
    }),
    // Broad cap source — toroidal circulation that flattens outward
    createEmitter('Mushroom Cap', {
      position: [0.5, 0.28, 0.5],
      radius: 0.115,
      startTime: 0.68,
      smokeLeadTime: 0.03,
      blastDuration: 0.5,
      plumeDuration: 8.0,
      densityYield: 1.6,
      heatYield: 14,
      fuelYield: 3.8,
      reactionYield: 2.0,
      radialImpulse: 58,
      liftDirection: [0, 1, 0],
      liftImpulse: 32,
      heatPatchiness: 0.92,
      patchScale: 40,
      coreHeat: 2.8,
      coreLift: 18,
      turbulence: 13,
      crumbleStrength: 8,
      implosionStrength: 1.8,
      expansionRate: 1.28,
      sustain: 0.46,
      mushroomStrength: 6.4,
      smokeEntrainment: 2.2,
      seed: 421,
    }),
    // Four crown rolls that unfurl around the cap perimeter
    createEmitter('Crown Roll — Left', {
      position: [0.42, 0.285, 0.515],
      radius: 0.062,
      startTime: 0.88,
      smokeLeadTime: 0.02,
      blastDuration: 0.4,
      plumeDuration: 6.8,
      densityYield: 1.1,
      heatYield: 7.5,
      fuelYield: 2.4,
      reactionYield: 1.4,
      radialImpulse: 40,
      liftDirection: [-0.54, 0.76, 0.14],
      liftImpulse: 22,
      heatPatchiness: 0.94,
      patchScale: 46,
      coreHeat: 1.2,
      coreLift: 9,
      turbulence: 12,
      crumbleStrength: 7,
      implosionStrength: 0.8,
      expansionRate: 0.86,
      sustain: 0.24,
      mushroomStrength: 4.8,
      smokeEntrainment: 1.4,
      seed: 433,
    }),
    createEmitter('Crown Roll — Right', {
      position: [0.59, 0.28, 0.474],
      radius: 0.066,
      startTime: 0.94,
      smokeLeadTime: 0.02,
      blastDuration: 0.38,
      plumeDuration: 6.6,
      densityYield: 1.05,
      heatYield: 7.2,
      fuelYield: 2.3,
      reactionYield: 1.3,
      radialImpulse: 42,
      liftDirection: [0.56, 0.75, -0.13],
      liftImpulse: 23,
      heatPatchiness: 0.93,
      patchScale: 48,
      coreHeat: 1.2,
      coreLift: 9,
      turbulence: 12,
      crumbleStrength: 7,
      implosionStrength: 0.8,
      expansionRate: 0.88,
      sustain: 0.22,
      mushroomStrength: 4.6,
      smokeEntrainment: 1.4,
      seed: 439,
    }),
    createEmitter('Crown Roll — Front', {
      position: [0.505, 0.282, 0.428],
      radius: 0.062,
      startTime: 0.91,
      smokeLeadTime: 0.02,
      blastDuration: 0.38,
      plumeDuration: 6.7,
      densityYield: 1.0,
      heatYield: 7.0,
      fuelYield: 2.2,
      reactionYield: 1.3,
      radialImpulse: 38,
      liftDirection: [0.07, 0.75, -0.62],
      liftImpulse: 21,
      heatPatchiness: 0.93,
      patchScale: 47,
      coreHeat: 1.1,
      coreLift: 8,
      turbulence: 11,
      crumbleStrength: 6.5,
      implosionStrength: 0.7,
      expansionRate: 0.84,
      sustain: 0.2,
      mushroomStrength: 4.2,
      smokeEntrainment: 1.3,
      seed: 443,
    }),
    createEmitter('Crown Roll — Back', {
      position: [0.495, 0.288, 0.576],
      radius: 0.064,
      startTime: 0.97,
      smokeLeadTime: 0.02,
      blastDuration: 0.38,
      plumeDuration: 6.5,
      densityYield: 1.02,
      heatYield: 6.8,
      fuelYield: 2.2,
      reactionYield: 1.2,
      radialImpulse: 39,
      liftDirection: [-0.07, 0.76, 0.62],
      liftImpulse: 21,
      heatPatchiness: 0.93,
      patchScale: 49,
      coreHeat: 1.1,
      coreLift: 8,
      turbulence: 11,
      crumbleStrength: 6.5,
      implosionStrength: 0.7,
      expansionRate: 0.86,
      sustain: 0.2,
      mushroomStrength: 4.0,
      smokeEntrainment: 1.3,
      seed: 449,
    }),
  ],
  lights: [
    createLight('High Sun', {
      lightType: 'directional',
      dirX: -0.42, dirY: 0.86, dirZ: 0.28,
      posX: 0.5, posY: 0.85, posZ: 0.5,
      intensity: 2.25,
      colorR: 1.0, colorG: 0.9, colorB: 0.78,
    }),
  ],
  runtimeParams: {
    wind: [0.012, 0, -0.008],
    windStrength: 0.06,
    buoyancy: 8.4,
    vorticityStrength: 5.8,
  },
  renderOutput: {
    stepCount: 448,
    scatteringForward: 0.38,
    scatteringBack: -0.22,
  },
}
