import { createScalarEmitter, createVelocityEmitter, createIgniterEmitter, createLight, type NewFilePreset } from './types'

export const artilleryBurstPreset: NewFilePreset = {
  id: 'artillery-burst',
  label: 'Artillery Airburst',
  description: 'Single shell burst: sharp flash, short impulse, then expanding dirty smoke.',
  emitters: [
    createScalarEmitter('Hot Core', {
      positionX: 0.5, positionY: 0.19, positionZ: 0.5,
      radius: 0.055,
      startTime: 0,
      duration: 0.11,
      densityRate: 3.2,
      heatRate: 16,
      fuelRate: 4.2,
      noiseScale: 60,
      noiseMix: 0.9,
      seed: 211,
    }),
    createVelocityEmitter('Shockwave', {
      positionX: 0.5, positionY: 0.19, positionZ: 0.5,
      radius: 0.065,
      startTime: 0,
      duration: 0.08,
      mode: 'radial',
      speed: 130,
      directionX: 0, directionY: 0, directionZ: 0,
      falloff: 0.25,
      seed: 223,
    }),
    createScalarEmitter('Dirty Smoke Ball', {
      positionX: 0.5, positionY: 0.19, positionZ: 0.5,
      radius: 0.075,
      startTime: 0.12,
      duration: 1.8,
      densityRate: 1.9,
      heatRate: 0.2,
      fuelRate: 0,
      noiseScale: 34,
      noiseMix: 0.78,
      seed: 229,
    }),
    createScalarEmitter('Falling Dust', {
      positionX: 0.5, positionY: 0.055, positionZ: 0.5,
      radius: 0.12,
      startTime: 0.25,
      duration: 2.4,
      densityRate: 1.7,
      heatRate: 0,
      fuelRate: 0,
      noiseScale: 28,
      noiseMix: 0.6,
      seed: 239,
    }),
    createVelocityEmitter('Dust Kick', {
      positionX: 0.5, positionY: 0.055, positionZ: 0.5,
      radius: 0.1,
      startTime: 0.08,
      duration: 0.25,
      mode: 'radial',
      speed: 24,
      directionX: 0, directionY: 0, directionZ: 0,
      falloff: 0.5,
      seed: 241,
    }),
    createIgniterEmitter('Ignition', {
      positionX: 0.5, positionY: 0.19, positionZ: 0.5,
      radius: 0.06,
      startTime: 0,
      duration: 0.1,
      intensity: 1.0,
      seed: 251,
    }),
  ],
  lights: [
    createLight('Overcast Sky', {
      lightType: 'directional',
      dirX: -0.28, dirY: 0.92, dirZ: 0.26,
      posX: 0.5, posY: 0.85, posZ: 0.5,
      intensity: 1.85,
      colorR: 0.92, colorG: 0.94, colorB: 1.0,
    }),
  ],
  runtimeParams: {
    wind: [0.032, 0, -0.018],
    windStrength: 0.28,
    gravity: [0, -1, 0],
    gravityStrength: 0.45,
    buoyancy: 3.5,
    vorticityStrength: 4.8,
    worldSize: 50,
  },
  renderOutput: {
    stepCount: 384,
    scatteringForward: 0.34,
    scatteringBack: -0.16,
  },
}
