import { createScalarEmitter, createVelocityEmitter, createLight, type NewFilePreset } from './types'

export const industrialSmokestacksPreset: NewFilePreset = {
  id: 'industrial-smokestacks',
  label: 'Industrial Smokestacks',
  description: 'Three separate stack plumes merging under a steady upper wind.',
  emitters: [
    createScalarEmitter('Stack A Smoke', {
      positionX: 0.32, positionY: 0.09, positionZ: 0.55,
      radius: 0.032,
      startTime: 0,
      duration: 9999,
      densityRate: 1.25,
      heatRate: 0.32,
      fuelRate: 0,
      noiseScale: 8,
      noiseMix: 0.58,
      seed: 1111,
    }),
    createScalarEmitter('Stack B Smoke', {
      positionX: 0.48, positionY: 0.08, positionZ: 0.5,
      radius: 0.04,
      startTime: 0.35,
      duration: 9999,
      densityRate: 1.55,
      heatRate: 0.25,
      fuelRate: 0,
      noiseScale: 9,
      noiseMix: 0.62,
      seed: 1123,
    }),
    createScalarEmitter('Stack C Smoke', {
      positionX: 0.64, positionY: 0.085, positionZ: 0.59,
      radius: 0.034,
      startTime: 0.7,
      duration: 9999,
      densityRate: 1.1,
      heatRate: 0.18,
      fuelRate: 0,
      noiseScale: 10,
      noiseMix: 0.64,
      seed: 1139,
    }),
    createVelocityEmitter('Stack A Draft', {
      positionX: 0.32, positionY: 0.095, positionZ: 0.55,
      radius: 0.045,
      startTime: 0,
      duration: 9999,
      mode: 'directional',
      speed: 5.8,
      directionX: 0.08, directionY: 1, directionZ: -0.02,
      falloff: 0.82,
      seed: 1151,
    }),
    createVelocityEmitter('Stack B Draft', {
      positionX: 0.48, positionY: 0.09, positionZ: 0.5,
      radius: 0.052,
      startTime: 0,
      duration: 9999,
      mode: 'directional',
      speed: 6.5,
      directionX: 0.1, directionY: 1, directionZ: -0.03,
      falloff: 0.84,
      seed: 1153,
    }),
    createVelocityEmitter('Shared Turbulence', {
      positionX: 0.52, positionY: 0.2, positionZ: 0.53,
      radius: 0.24,
      startTime: 1.1,
      duration: 9999,
      mode: 'turbulent',
      speed: 2.5,
      directionX: 0, directionY: 1, directionZ: 0,
      falloff: 0.96,
      seed: 1163,
    }),
  ],
  lights: [
    createLight('Low Sun', {
      lightType: 'directional',
      dirX: -0.5, dirY: 0.78, dirZ: 0.36,
      posX: 0.5, posY: 0.8, posZ: 0.5,
      intensity: 1.55,
      colorR: 1.0, colorG: 0.9, colorB: 0.76,
    }),
  ],
  runtimeParams: {
    wind: [0.075, 0, -0.018],
    windStrength: 0.36,
    gravity: [0, -1, 0],
    gravityStrength: 0.45,
    buoyancy: 1.85,
    vorticityStrength: 2.2,
    worldSize: 45,
  },
  renderOutput: {
    displayMode: 'density',
    stepCount: 420,
    scatteringForward: 0.25,
    scatteringBack: -0.1,
  },
}
