import { createEmitter, createLight, type NewFilePreset } from './types'

// Artillery HE airburst: fast, compact, asymmetric — nothing like a nuclear blast.
// The detonation is tiny but extremely violent. The fireball is short-lived; what
// persists is a ragged, asymmetric smoke ring that expands outward and upward.
// A second charge simulates the ground-struck fragment scatter that adds a low dirty
// haze beneath the ring.
export const artilleryBurstPreset: NewFilePreset = {
  id: 'artillery-burst',
  label: 'Artillery Airburst',
  description: 'Compact violent detonation with a fast-expanding smoke ring and debris haze.',
  emitters: [
    // The burst itself — very short, very hot, moderate radius
    createEmitter('Detonation', {
      position: [0.5, 0.2, 0.5],
      radius: 0.068,
      startTime: 0,
      smokeLeadTime: 0,
      blastDuration: 0.06,
      plumeDuration: 2.8,
      densityYield: 0.72,
      heatYield: 32,
      fuelYield: 7.5,
      reactionYield: 6.2,
      radialImpulse: 172,
      liftDirection: [0, 1, 0],
      liftImpulse: 14,
      heatPatchiness: 0.95,
      patchScale: 68,
      coreHeat: 4.2,
      coreLift: 8,
      turbulence: 22,
      crumbleStrength: 18,
      implosionStrength: 14,
      expansionRate: 1.85,
      sustain: 0.08,
      mushroomStrength: 0.6,
      smokeEntrainment: 1.2,
      seed: 211,
    }),
    // Expanding annular smoke ring that persists after the fireball
    createEmitter('Smoke Ring', {
      position: [0.5, 0.2, 0.5],
      radius: 0.088,
      startTime: 0.08,
      smokeLeadTime: 0,
      blastDuration: 0.18,
      plumeDuration: 5.0,
      densityYield: 1.45,
      heatYield: 6.5,
      fuelYield: 1.8,
      reactionYield: 0.8,
      radialImpulse: 88,
      liftDirection: [0, 1, 0],
      liftImpulse: 6,
      heatPatchiness: 0.88,
      patchScale: 52,
      coreHeat: 0.6,
      coreLift: 3,
      turbulence: 14,
      crumbleStrength: 10,
      implosionStrength: 2.5,
      expansionRate: 1.42,
      sustain: 0.12,
      mushroomStrength: 2.2,
      smokeEntrainment: 0.5,
      seed: 223,
    }),
    // Low ground haze from fragment cratering / disturbed earth
    createEmitter('Ground Haze', {
      position: [0.5, 0.07, 0.5],
      radius: 0.095,
      startTime: 0.04,
      smokeLeadTime: 0,
      blastDuration: 0.28,
      plumeDuration: 3.5,
      densityYield: 1.05,
      heatYield: 3.5,
      fuelYield: 0.8,
      reactionYield: 0.4,
      radialImpulse: 55,
      liftDirection: [0, 1, 0],
      liftImpulse: 4,
      heatPatchiness: 0.78,
      patchScale: 40,
      coreHeat: 0.3,
      coreLift: 2,
      turbulence: 9,
      crumbleStrength: 6,
      implosionStrength: 0.5,
      expansionRate: 0.78,
      sustain: 0.06,
      mushroomStrength: 0.4,
      smokeEntrainment: 0.8,
      seed: 233,
    }),
  ],
  lights: [
    createLight('Overcast Sky', {
      lightType: 'directional',
      dirX: -0.28, dirY: 0.92, dirZ: 0.26,
      posX: 0.5, posY: 0.85, posZ: 0.5,
      intensity: 1.85,
      colorR: 0.92, colorG: 0.94, colorB: 1.0,
    }),
  ],
  runtimeParams: {
    wind: [0.032, 0, -0.018],
    windStrength: 0.22,
    buoyancy: 4.8,
    vorticityStrength: 4.2,
  },
  renderOutput: {
    stepCount: 384,
    scatteringForward: 0.34,
    scatteringBack: -0.16,
  },
}
