import { createEmitter, createLight, type NewFilePreset } from './types'

// Volcanic Plinian eruption column: far slower, far denser than any explosion.
// The vent blasts upward in a sustained, high-momentum jet. The jet column
// transitions to a convective plume at altitude. Pyroclastic density and
// tephra rain create a very different visual rhythm from combustion-based events.
export const volcanicEruptionPreset: NewFilePreset = {
  id: 'volcanic-eruption',
  label: 'Volcanic Eruption',
  description: 'Plinian eruption column — dense jet, convective plume, and ash umbrella.',
  emitters: [
    // Vent jet — extremely high impulse, very sustained, dense
    createEmitter('Vent Jet', {
      position: [0.5, 0.06, 0.5],
      radius: 0.058,
      startTime: 0,
      smokeLeadTime: 0.5,
      blastDuration: 30,
      plumeDuration: 60,
      densityYield: 2.8,
      heatYield: 18,
      fuelYield: 4.5,
      reactionYield: 1.8,
      radialImpulse: 6,
      liftDirection: [0, 1, 0],
      liftImpulse: 22,
      heatPatchiness: 0.42,
      patchScale: 14,
      coreHeat: 7.2,
      coreLift: 28,
      turbulence: 5.5,
      crumbleStrength: 3.8,
      implosionStrength: 0,
      expansionRate: 0.38,
      sustain: 3.5,
      mushroomStrength: 0.2,
      smokeEntrainment: 1.8,
      seed: 501,
    }),
    // Mid-column broadening — the convective transition zone
    createEmitter('Convective Column', {
      position: [0.5, 0.18, 0.5],
      radius: 0.082,
      startTime: 1.8,
      smokeLeadTime: 0,
      blastDuration: 30,
      plumeDuration: 60,
      densityYield: 2.2,
      heatYield: 8.5,
      fuelYield: 1.8,
      reactionYield: 0.6,
      radialImpulse: 5,
      liftDirection: [0.02, 1, -0.015],
      liftImpulse: 16,
      heatPatchiness: 0.65,
      patchScale: 22,
      coreHeat: 3.2,
      coreLift: 18,
      turbulence: 7.5,
      crumbleStrength: 5.2,
      implosionStrength: 0,
      expansionRate: 0.72,
      sustain: 2.8,
      mushroomStrength: 0.5,
      smokeEntrainment: 3.5,
      seed: 523,
    }),
    // Ash umbrella spreading laterally at altitude — high density, near-zero lift
    createEmitter('Ash Umbrella', {
      position: [0.5, 0.35, 0.5],
      radius: 0.13,
      startTime: 4.5,
      smokeLeadTime: 0,
      blastDuration: 30,
      plumeDuration: 60,
      densityYield: 1.85,
      heatYield: 2.5,
      fuelYield: 0.4,
      reactionYield: 0.1,
      radialImpulse: 18,
      liftDirection: [0, 1, 0],
      liftImpulse: 3.5,
      heatPatchiness: 0.82,
      patchScale: 42,
      coreHeat: 0.5,
      coreLift: 1.8,
      turbulence: 9.5,
      crumbleStrength: 6.5,
      implosionStrength: 0,
      expansionRate: 1.35,
      sustain: 2.2,
      mushroomStrength: 3.8,
      smokeEntrainment: 0.8,
      seed: 541,
    }),
  ],
  lights: [
    createLight('Tropical Sun', {
      lightType: 'directional',
      dirX: -0.22, dirY: 0.94, dirZ: 0.26,
      posX: 0.5, posY: 0.9, posZ: 0.5,
      intensity: 2.4,
      colorR: 1.0, colorG: 0.98, colorB: 0.88,
    }),
  ],
  runtimeParams: {
    wind: [0.042, 0, -0.022],
    windStrength: 0.28,
    buoyancy: 6.8,
    vorticityStrength: 3.5,
  },
  renderOutput: {
    stepCount: 440,
    scatteringForward: 0.24,
    scatteringBack: -0.1,
  },
}
