import { createEmitter, createLight, type NewFilePreset } from './types'

export const campfirePreset: NewFilePreset = {
  id: 'campfire',
  label: 'Campfire',
  description: 'Low sustained flame with a turbulent thermal column and drifting smoke.',
  emitters: [
    // Hot core — the actual flame bed sitting just above the logs
    createEmitter('Flame Bed', {
      position: [0.5, 0.058, 0.5],
      radius: 0.038,
      startTime: 0,
      smokeLeadTime: 0,
      blastDuration: 12,
      plumeDuration: 30,
      densityYield: 0.55,
      heatYield: 9.2,
      fuelYield: 8.8,
      reactionYield: 1.8,
      radialImpulse: 2.5,
      liftDirection: [0, 1, 0],
      liftImpulse: 5.5,
      heatPatchiness: 0.28,
      patchScale: 10,
      coreHeat: 4.2,
      coreLift: 5.8,
      turbulence: 3.4,
      crumbleStrength: 2.2,
      implosionStrength: 0,
      expansionRate: 0.28,
      sustain: 1.8,
      mushroomStrength: 0.1,
      smokeEntrainment: 0.5,
      seed: 607,
    }),
    // Wider, cooler smoke column that rises and drifts
    createEmitter('Smoke Column', {
      position: [0.5, 0.085, 0.5],
      radius: 0.062,
      startTime: 0.4,
      smokeLeadTime: 0,
      blastDuration: 14,
      plumeDuration: 30,
      densityYield: 1.2,
      heatYield: 2.8,
      fuelYield: 1.4,
      reactionYield: 0.4,
      radialImpulse: 1.2,
      liftDirection: [0.04, 1, -0.03],
      liftImpulse: 4.2,
      heatPatchiness: 0.52,
      patchScale: 18,
      coreHeat: 1.0,
      coreLift: 2.8,
      turbulence: 2.2,
      crumbleStrength: 1.4,
      implosionStrength: 0,
      expansionRate: 0.45,
      sustain: 1.4,
      mushroomStrength: 0.05,
      smokeEntrainment: 0.8,
      seed: 613,
    }),
  ],
  lights: [
    createLight('Warm Overcast Sky', {
      lightType: 'directional',
      dirX: -0.24, dirY: 0.95, dirZ: 0.18,
      posX: 0.5, posY: 0.82, posZ: 0.5,
      intensity: 1.15,
      colorR: 1.0, colorG: 0.86, colorB: 0.68,
    }),
  ],
  runtimeParams: {
    wind: [0.018, 0, -0.012],
    windStrength: 0.04,
    buoyancy: 2.8,
    vorticityStrength: 1.05,
  },
  renderOutput: {
    stepCount: 320,
    scatteringForward: 0.26,
    scatteringBack: -0.11,
  },
}
