import { createScalarEmitter, createVelocityEmitter, createLight, type NewFilePreset } from './types'

export const smokeGrenadeClusterPreset: NewFilePreset = {
  id: 'smoke-grenade-cluster',
  label: 'Smoke Grenade Cluster',
  description: 'Three cool smoke canisters blooming at staggered times across the ground.',
  emitters: [
    createScalarEmitter('Canister Left', {
      positionX: 0.34, positionY: 0.055, positionZ: 0.56,
      radius: 0.038,
      startTime: 0,
      duration: 7.5,
      densityRate: 1.65,
      heatRate: 0.04,
      fuelRate: 0,
      noiseScale: 16,
      noiseMix: 0.9,
      seed: 1213,
    }),
    createScalarEmitter('Canister Center', {
      positionX: 0.5, positionY: 0.055, positionZ: 0.46,
      radius: 0.04,
      startTime: 0.9,
      duration: 8.0,
      densityRate: 1.9,
      heatRate: 0.04,
      fuelRate: 0,
      noiseScale: 18,
      noiseMix: 0.92,
      seed: 1229,
    }),
    createScalarEmitter('Canister Right', {
      positionX: 0.66, positionY: 0.055, positionZ: 0.57,
      radius: 0.036,
      startTime: 1.7,
      duration: 7.0,
      densityRate: 1.55,
      heatRate: 0.03,
      fuelRate: 0,
      noiseScale: 17,
      noiseMix: 0.92,
      seed: 1237,
    }),
    createVelocityEmitter('Low Ground Spill', {
      positionX: 0.5, positionY: 0.055, positionZ: 0.52,
      radius: 0.24,
      startTime: 0.2,
      duration: 7.5,
      mode: 'radial',
      speed: 6.2,
      directionX: 0, directionY: 0, directionZ: 0,
      falloff: 0.8,
      tightness: 0.16,
      seed: 1249,
    }),
    createVelocityEmitter('Slow Billow', {
      positionX: 0.5, positionY: 0.12, positionZ: 0.52,
      radius: 0.26,
      startTime: 1.2,
      duration: 9999,
      mode: 'turbulent',
      speed: 3.6,
      directionX: 0, directionY: 1, directionZ: 0,
      falloff: 0.95,
      tightness: 0.08,
      seed: 1259,
    }),
  ],
  lights: [
    createLight('Flat Sky', {
      lightType: 'directional',
      dirX: -0.2, dirY: 0.96, dirZ: 0.18,
      posX: 0.5, posY: 0.86, posZ: 0.5,
      intensity: 1.45,
      colorR: 0.94, colorG: 0.96, colorB: 1.0,
    }),
  ],
  runtimeParams: {
    wind: [0.038, 0, -0.01],
    windStrength: 0.16,
    gravity: [0, -1, 0],
    gravityStrength: 0.45,
    buoyancy: 0.95,
    vorticityStrength: 3.2,
    vorticityConstantMask: 0.5,
    vorticityVelocityMask: 0.5,
    vorticityHeatMask: 0,
    vorticityDensityMask: 1.25,
    worldSize: 22,
  },
  renderOutput: {
    displayMode: 'density',
    stepCount: 430,
    scatteringForward: 0.3,
    scatteringBack: -0.14,
  },
}
