import { createBurstEmitter, createScalarEmitter, createVelocityEmitter, createLight, type NewFilePreset } from './types'

export const demolitionDustPreset: NewFilePreset = {
  id: 'demolition-dust',
  label: 'Demolition Dust',
  description: 'Sequential floor-collapse pulses that settle into a heavy rolling street-level cloud.',
  emitters: [
    createBurstEmitter('First Floor Pancake', {
      positionX: 0.44, positionY: 0.065, positionZ: 0.52,
      radius: 0.14,
      startTime: 0,
      duration: 0.5,
      densityAmount: 1.3,
      heatAmount: 0,
      fuelAmount: 0,
      reactionAmount: 0,
      expansionSpeed: 28,
      liftSpeed: 4,
      turbulenceSpeed: 20,
      falloff: 0.62,
      noiseScale: 12,
      noiseMix: 0.72,
      seed: 1711,
    }),
    createBurstEmitter('Second Floor Pancake', {
      positionX: 0.57, positionY: 0.075, positionZ: 0.47,
      radius: 0.17,
      startTime: 1.15,
      duration: 0.65,
      densityAmount: 1.65,
      heatAmount: 0,
      fuelAmount: 0,
      reactionAmount: 0,
      expansionSpeed: 34,
      liftSpeed: 6,
      turbulenceSpeed: 24,
      falloff: 0.6,
      noiseScale: 11,
      noiseMix: 0.74,
      seed: 1733,
    }),
    createScalarEmitter('Concrete Powder Feed', {
      positionX: 0.52, positionY: 0.055, positionZ: 0.5,
      radius: 0.2,
      startTime: 1.9,
      duration: 4.4,
      densityRate: 0.95,
      heatRate: 0,
      fuelRate: 0,
      noiseScale: 10,
      noiseMix: 0.78,
      seed: 1747,
    }),
    createVelocityEmitter('Street Rollout', {
      positionX: 0.52, positionY: 0.055, positionZ: 0.5,
      radius: 0.31,
      startTime: 0.55,
      duration: 5.5,
      mode: 'radial',
      speed: 8.5,
      directionX: 0, directionY: 0, directionZ: 0,
      falloff: 0.78,
      tightness: 0.1,
      seed: 1721,
    }),
    createVelocityEmitter('Collapse Boil', {
      positionX: 0.52, positionY: 0.12, positionZ: 0.5,
      radius: 0.28,
      startTime: 1.2,
      duration: 7,
      mode: 'turbulent',
      speed: 3.8,
      directionX: 0, directionY: 1, directionZ: 0,
      falloff: 0.92,
      tightness: 0.08,
      seed: 1753,
    }),
  ],
  lights: [
    createLight('Dusty Sun', {
      lightType: 'directional',
      dirX: -0.42, dirY: 0.82, dirZ: 0.28,
      posX: 0.5, posY: 0.8, posZ: 0.5,
      intensity: 1.6,
      colorR: 1.0, colorG: 0.92, colorB: 0.78,
    }),
  ],
  runtimeParams: {
    wind: [0.035, 0, -0.012],
    windStrength: 0.16,
    gravity: [0, -1, 0],
    gravityStrength: 0.62,
    buoyancy: 0.42,
    vorticityStrength: 3.4,
    vorticityConstantMask: 0.65,
    vorticityVelocityMask: 0.55,
    vorticityHeatMask: 0,
    vorticityDensityMask: 1.25,
    worldSize: 60,
  },
  renderOutput: {
    displayMode: 'density',
    stepCount: 470,
    scatteringForward: 0.24,
    scatteringBack: -0.09,
  },
}
