import { createBurstEmitter, createScalarEmitter, createVelocityEmitter, createLight, type NewFilePreset } from './types'

export const fuelTankExplosionPreset: NewFilePreset = {
  id: 'fuel-tank-explosion',
  label: 'Fuel Tank Explosion',
  description: 'Hydrocarbon vapor flash, rolling fireball, black soot column, and low dust rollout.',
  emitters: [
    createBurstEmitter('Vapor Cloud Deflagration', {
      positionX: 0.5, positionY: 0.1, positionZ: 0.5,
      radius: 0.115,
      startTime: 0,
      duration: 0.18,
      densityAmount: 0.2,
      heatAmount: 1.65,
      fuelAmount: 1.65,
      reactionAmount: 0.95,
      expansionSpeed: 82,
      liftSpeed: 34,
      turbulenceSpeed: 32,
      falloff: 0.42,
      noiseScale: 16,
      noiseMix: 0.74,
      seed: 1411,
    }),
    createBurstEmitter('Tank Shell Dust', {
      positionX: 0.5, positionY: 0.055, positionZ: 0.5,
      radius: 0.16,
      startTime: 0.22,
      duration: 0.34,
      densityAmount: 0.26,
      heatAmount: 0,
      fuelAmount: 0,
      reactionAmount: 0,
      expansionSpeed: 24,
      liftSpeed: -4,
      turbulenceSpeed: 24,
      falloff: 0.54,
      noiseScale: 12,
      noiseMix: 0.62,
      seed: 1423,
    }),
    createScalarEmitter('Burning Fuel Feed', {
      positionX: 0.51, positionY: 0.11, positionZ: 0.49,
      radius: 0.052,
      startTime: 0.16,
      duration: 4.2,
      densityRate: 0.22,
      heatRate: 13.5,
      fuelRate: 13.0,
      noiseScale: 30,
      noiseMix: 0.82,
      seed: 1439,
    }),
    createScalarEmitter('Black Soot Pull', {
      positionX: 0.54, positionY: 0.21, positionZ: 0.47,
      radius: 0.08,
      startTime: 1.15,
      duration: 5.0,
      densityRate: 1.65,
      heatRate: 0.55,
      fuelRate: 0.08,
      noiseScale: 24,
      noiseMix: 0.78,
      seed: 1451,
    }),
    createVelocityEmitter('Rolling Fireball Lift', {
      positionX: 0.52, positionY: 0.16, positionZ: 0.49,
      radius: 0.13,
      startTime: 0.22,
      duration: 3.6,
      mode: 'directional',
      speed: 34,
      directionX: 0.09, directionY: 1, directionZ: -0.04,
      falloff: 0.74,
      tightness: 0.24,
      seed: 1447,
    }),
    createVelocityEmitter('Fireball Roll Turbulence', {
      positionX: 0.54, positionY: 0.25, positionZ: 0.48,
      radius: 0.17,
      startTime: 0.65,
      duration: 4.2,
      mode: 'turbulent',
      speed: 18,
      directionX: 0, directionY: 0, directionZ: 0,
      falloff: 0.62,
      tightness: 0.1,
      seed: 1459,
    }),
    createVelocityEmitter('Dust Rollout', {
      positionX: 0.5, positionY: 0.052, positionZ: 0.5,
      radius: 0.24,
      startTime: 0.25,
      duration: 1.5,
      mode: 'radial',
      speed: 22,
      directionX: 0, directionY: 0, directionZ: 0,
      falloff: 0.68,
      tightness: 0.18,
      seed: 1471,
    }),
  ],
  lights: [
    createLight('Industrial Yard Sun', {
      lightType: 'directional',
      dirX: -0.26, dirY: 0.93, dirZ: 0.24,
      posX: 0.5, posY: 0.86, posZ: 0.5,
      intensity: 2.1,
      colorR: 1.0, colorG: 0.95, colorB: 0.86,
    }),
  ],
  runtimeParams: {
    wind: [0.05, 0, -0.022],
    windStrength: 0.24,
    gravity: [0, -1, 0],
    gravityStrength: 0.43,
    buoyancy: 5.8,
    vorticityStrength: 6.4,
    vorticityConstantMask: 0.7,
    vorticityVelocityMask: 0.75,
    vorticityHeatMask: 1.25,
    vorticityDensityMask: 0.8,
    worldSize: 85,
  },
  renderOutput: {
    stepCount: 500,
    scatteringForward: 0.22,
    scatteringBack: -0.09,
  },
}
