import { createScalarEmitter, createVelocityEmitter, createIgniterEmitter, createLight, type NewFilePreset } from './types'

export const oilWellFirePreset: NewFilePreset = {
  id: 'oil-well-fire',
  label: 'Oil Well Fire',
  description: 'Fuel-rich jet fire with a black soot column bent hard by crosswind.',
  emitters: [
    createScalarEmitter('Wellhead Flame', {
      positionX: 0.5, positionY: 0.055, positionZ: 0.5,
      radius: 0.032,
      startTime: 0,
      duration: 9999,
      densityRate: 0.25,
      heatRate: 12,
      fuelRate: 12,
      noiseScale: 8,
      noiseMix: 0.35,
      seed: 811,
    }),
    createVelocityEmitter('Jet Momentum', {
      positionX: 0.5, positionY: 0.06, positionZ: 0.5,
      radius: 0.038,
      startTime: 0,
      duration: 9999,
      mode: 'directional',
      speed: 18,
      directionX: 0.04, directionY: 1, directionZ: -0.02,
      falloff: 0.65,
      seed: 819,
    }),
    createScalarEmitter('Early Black Soot', {
      positionX: 0.51, positionY: 0.11, positionZ: 0.493,
      radius: 0.062,
      startTime: 0.75,
      duration: 9999,
      densityRate: 3.6,
      heatRate: 0.3,
      fuelRate: 0,
      noiseScale: 18,
      noiseMix: 0.65,
      seed: 827,
    }),
    createScalarEmitter('Downwind Soot Feed', {
      positionX: 0.548, positionY: 0.145, positionZ: 0.474,
      radius: 0.078,
      startTime: 2.0,
      duration: 9999,
      densityRate: 2.6,
      heatRate: 0.05,
      fuelRate: 0,
      noiseScale: 14,
      noiseMix: 0.72,
      seed: 839,
    }),
    createVelocityEmitter('Column Shear', {
      positionX: 0.53, positionY: 0.13, positionZ: 0.485,
      radius: 0.11,
      startTime: 0.8,
      duration: 9999,
      mode: 'directional',
      speed: 7.5,
      directionX: 0.8, directionY: 0.45, directionZ: -0.35,
      falloff: 0.85,
      seed: 847,
    }),
    createIgniterEmitter('Ignition', {
      positionX: 0.5, positionY: 0.06, positionZ: 0.5,
      radius: 0.04,
      startTime: 0,
      duration: 0.2,
      intensity: 1.0,
      seed: 853,
    }),
  ],
  lights: [
    createLight('Harsh Noon Sun', {
      lightType: 'directional',
      dirX: -0.18, dirY: 0.96, dirZ: 0.22,
      posX: 0.5, posY: 0.9, posZ: 0.5,
      intensity: 2.8,
      colorR: 1.0, colorG: 0.97, colorB: 0.92,
    }),
  ],
  runtimeParams: {
    wind: [0.095, 0, -0.04],
    windStrength: 0.7,
    gravity: [0, -1, 0],
    gravityStrength: 0.45,
    buoyancy: 4.4,
    vorticityStrength: 3.1,
    worldSize: 30,
  },
  renderOutput: {
    stepCount: 420,
    scatteringForward: 0.16,
    scatteringBack: -0.05,
  },
}
