import { createScalarEmitter, createVelocityEmitter, createLight, type NewFilePreset } from './types'

export const steadySmokeCrosswindPreset: NewFilePreset = {
  id: 'steady-smoke-crosswind',
  label: 'Steady Smoke Crosswind',
  description: 'Continuous cool smoke plume with a believable sideways wind shear.',
  emitters: [
    createScalarEmitter('Smoke Source', {
      positionX: 0.35, positionY: 0.06, positionZ: 0.56,
      radius: 0.045,
      startTime: 0,
      duration: 9999,
      densityRate: 1.7,
      heatRate: 0.18,
      fuelRate: 0,
      noiseScale: 7,
      noiseMix: 0.62,
      seed: 1011,
    }),
    createVelocityEmitter('Gentle Updraft', {
      positionX: 0.35, positionY: 0.07, positionZ: 0.56,
      radius: 0.08,
      startTime: 0,
      duration: 9999,
      mode: 'directional',
      speed: 5.4,
      directionX: 0.18, directionY: 1, directionZ: -0.06,
      falloff: 0.9,
      tightness: 0.18,
      seed: 1031,
    }),
    createVelocityEmitter('Plume Ruffle', {
      positionX: 0.48, positionY: 0.18, positionZ: 0.5,
      radius: 0.2,
      startTime: 0.8,
      duration: 9999,
      mode: 'turbulent',
      speed: 3.0,
      directionX: 0, directionY: 1, directionZ: 0,
      falloff: 0.95,
      tightness: 0.06,
      seed: 1033,
    }),
  ],
  lights: [
    createLight('Soft Overcast', {
      lightType: 'directional',
      dirX: -0.28, dirY: 0.92, dirZ: 0.22,
      posX: 0.5, posY: 0.85, posZ: 0.5,
      intensity: 1.3,
      colorR: 0.92, colorG: 0.95, colorB: 1.0,
    }),
  ],
  runtimeParams: {
    wind: [0.09, 0, -0.025],
    windStrength: 0.42,
    gravity: [0, -1, 0],
    gravityStrength: 0.45,
    buoyancy: 1.55,
    vorticityStrength: 2.6,
    vorticityConstantMask: 0.6,
    vorticityVelocityMask: 0.45,
    vorticityHeatMask: 0.3,
    vorticityDensityMask: 1.0,
    worldSize: 14,
  },
  renderOutput: {
    displayMode: 'density',
    stepCount: 380,
    scatteringForward: 0.28,
    scatteringBack: -0.12,
  },
}
