import { createEmitter, createLight, type NewFilePreset } from './types'

// Oil well fire: a narrow, intensely hot flame base feeding a massive sooty column.
// Uses the long-blastDuration trick (same as campfire) for sustained emission.
// Two sources: a tight hot core and a wide dense smoke column above it.
// The wind shears the top into rolling lobes.
// Key differences from campfire: much higher densityYield (dense black soot),
// very high heatYield to keep the core burning, stronger wind.
export const oilWellFirePreset: NewFilePreset = {
  id: 'oil-well-fire',
  label: 'Oil Well Fire',
  description: 'Tight intensely hot flame feeding a dense sooty column sheared by crosswind.',
  emitters: [
    createEmitter('Flame Base', {
      position: [0.5, 0.055, 0.5],
      radius: 0.038,
      startTime: 0,
      smokeLeadTime: 0,
      blastDuration: 22,
      plumeDuration: 60,
      densityYield: 0.35,
      heatYield: 16,
      fuelYield: 13.5,
      reactionYield: 2.0,
      radialImpulse: 2.0,
      liftDirection: [0, 1, 0],
      liftImpulse: 9.5,
      heatPatchiness: 0.18,
      patchScale: 7,
      coreHeat: 7.5,
      coreLift: 14,
      turbulence: 3.8,
      crumbleStrength: 2.5,
      implosionStrength: 0,
      expansionRate: 0.2,
      sustain: 3.2,
      mushroomStrength: 0.06,
      smokeEntrainment: 0.45,
      seed: 811,
    }),
    createEmitter('Soot Column', {
      position: [0.5, 0.09, 0.5],
      radius: 0.072,
      startTime: 1.5,
      smokeLeadTime: 0,
      blastDuration: 22,
      plumeDuration: 60,
      densityYield: 3.5,
      heatYield: 2.8,
      fuelYield: 1.6,
      reactionYield: 0.35,
      radialImpulse: 1.5,
      liftDirection: [0.05, 1, -0.03],
      liftImpulse: 5.8,
      heatPatchiness: 0.68,
      patchScale: 22,
      coreHeat: 1.2,
      coreLift: 4.8,
      turbulence: 3.2,
      crumbleStrength: 2.2,
      implosionStrength: 0,
      expansionRate: 0.55,
      sustain: 2.2,
      mushroomStrength: 0.08,
      smokeEntrainment: 1.2,
      seed: 827,
    }),
  ],
  lights: [
    createLight('Harsh Noon Sun', {
      lightType: 'directional',
      dirX: -0.18, dirY: 0.96, dirZ: 0.22,
      posX: 0.5, posY: 0.9, posZ: 0.5,
      intensity: 2.8,
      colorR: 1.0, colorG: 0.97, colorB: 0.92,
    }),
  ],
  runtimeParams: {
    wind: [0.08, 0, -0.035],
    windStrength: 0.55,
    buoyancy: 5.0,
    vorticityStrength: 2.6,
    worldSize: 30,
  },
  renderOutput: {
    stepCount: 360,
    scatteringForward: 0.18,
    scatteringBack: -0.06,
  },
}
