import { createScalarEmitter, createVelocityEmitter, createLight, type NewFilePreset } from './types'

// Industrial smokestacks: the "three blobs" problem comes from slow upward velocity and
// low noise. Real stack plumes are COLUMN-shaped — narrow at the base, spreading and
// bending in the wind above. Fix: tight collocated velocity+scalar at the source,
// strong enough to form a column before lateral wind bends it. Stagger heights and
// rates for variety. Add strong horizontal wind shear that kicks in above the stacks.
export const industrialSmokestacksPreset: NewFilePreset = {
  id: 'industrial-smokestacks',
  label: 'Industrial Smokestacks',
  description: 'Three staggered stack plumes rising as tight columns before bending in upper wind.',
  emitters: [
    // Stack A — tallest, heaviest. heatRate kept very low — industrial exhaust is warm, not burning.
    // Anything above ~0.08 heatRate will trigger combustion glow near the source.
    createScalarEmitter('Stack A Smoke', {
      positionX: 0.3, positionY: 0.09, positionZ: 0.55,
      radius: 0.018,
      startTime: 0,
      duration: 9999,
      densityRate: 2.2,
      heatRate: 0.04,
      fuelRate: 0,
      noiseScale: 22,
      noiseMix: 0.78,
      seed: 1111,
    }),
    createVelocityEmitter('Stack A Jet', {
      positionX: 0.3, positionY: 0.09, positionZ: 0.55,
      radius: 0.022,
      startTime: 0,
      duration: 9999,
      mode: 'directional',
      speed: 14,
      directionX: 0.04, directionY: 1, directionZ: -0.02,
      falloff: 0.94,
      tightness: 0.55,
      seed: 1119,
    }),
    // Stack B
    createScalarEmitter('Stack B Smoke', {
      positionX: 0.5, positionY: 0.09, positionZ: 0.46,
      radius: 0.016,
      startTime: 0.6,
      duration: 9999,
      densityRate: 1.9,
      heatRate: 0.04,
      fuelRate: 0,
      noiseScale: 24,
      noiseMix: 0.8,
      seed: 1123,
    }),
    createVelocityEmitter('Stack B Jet', {
      positionX: 0.5, positionY: 0.09, positionZ: 0.46,
      radius: 0.02,
      startTime: 0.6,
      duration: 9999,
      mode: 'directional',
      speed: 12,
      directionX: 0.06, directionY: 1, directionZ: -0.03,
      falloff: 0.94,
      tightness: 0.52,
      seed: 1129,
    }),
    // Stack C — smaller
    createScalarEmitter('Stack C Smoke', {
      positionX: 0.68, positionY: 0.09, positionZ: 0.58,
      radius: 0.014,
      startTime: 1.2,
      duration: 9999,
      densityRate: 1.4,
      heatRate: 0.03,
      fuelRate: 0,
      noiseScale: 26,
      noiseMix: 0.82,
      seed: 1137,
    }),
    createVelocityEmitter('Stack C Jet', {
      positionX: 0.68, positionY: 0.09, positionZ: 0.58,
      radius: 0.018,
      startTime: 1.2,
      duration: 9999,
      mode: 'directional',
      speed: 10,
      directionX: 0.05, directionY: 1, directionZ: -0.02,
      falloff: 0.93,
      tightness: 0.5,
      seed: 1143,
    }),
    // Upper cross-wind bends the columns after they clear the stack tops
    createVelocityEmitter('Upper Crosswind', {
      positionX: 0.5, positionY: 0.38, positionZ: 0.5,
      radius: 0.42,
      startTime: 0.4,
      duration: 9999,
      mode: 'directional',
      speed: 12,
      directionX: 0.82, directionY: 0.08, directionZ: -0.22,
      falloff: 0.88,
      tightness: 0.04,
      seed: 1151,
    }),
    // Column turbulence
    createVelocityEmitter('Column Shear', {
      positionX: 0.48, positionY: 0.22, positionZ: 0.52,
      radius: 0.32,
      startTime: 0.8,
      duration: 9999,
      mode: 'turbulent',
      speed: 5.0,
      directionX: 0, directionY: 1, directionZ: 0,
      falloff: 0.96,
      tightness: 0.05,
      seed: 1163,
    }),
  ],
  lights: [
    createLight('Industrial Haze Sun', {
      lightType: 'directional',
      dirX: -0.55, dirY: 0.72, dirZ: 0.38,
      posX: 0.5, posY: 0.8, posZ: 0.5,
      intensity: 1.45,
      colorR: 1.0, colorG: 0.88, colorB: 0.72,
    }),
  ],
  runtimeParams: {
    wind: [0.055, 0, -0.015],
    windStrength: 0.35,
    gravity: [0, -1, 0],
    gravityStrength: 0.42,
    buoyancy: 0.8,
    vorticityStrength: 2.2,
    vorticityConstantMask: 0.4,
    vorticityVelocityMask: 0.5,
    vorticityHeatMask: 0.0,
    vorticityDensityMask: 0.5,
    worldSize: 30,
  },
  renderOutput: {
    displayMode: 'density',
    stepCount: 460,
    scatteringForward: 0.22,
    scatteringBack: -0.1,
  },
}
