import { createBurstEmitter, createScalarEmitter, createVelocityEmitter, createLight, type NewFilePreset } from './types'

export const artilleryBurstPreset: NewFilePreset = {
  id: 'artillery-burst',
  label: 'Artillery Airburst',
  description: 'Sharp dirty burst with a ragged pressure shell and falling debris smoke.',
  emitters: [
    createBurstEmitter('Shell Burst Core', {
      positionX: 0.5, positionY: 0.2, positionZ: 0.5,
      radius: 0.055,
      startTime: 0,
      duration: 0.09,
      densityAmount: 0.24,
      heatAmount: 1.2,
      fuelAmount: 0.28,
      reactionAmount: 0.54,
      expansionSpeed: 92,
      liftSpeed: 6,
      turbulenceSpeed: 32,
      falloff: 0.32,
      noiseScale: 22,
      noiseMix: 0.78,
      seed: 211,
    }),
    createScalarEmitter('Dirty Hanging Smoke', {
      positionX: 0.5, positionY: 0.19, positionZ: 0.5,
      radius: 0.055,
      startTime: 0.1,
      duration: 1.1,
      densityRate: 0.9,
      heatRate: 0.18,
      fuelRate: 0,
      noiseScale: 30,
      noiseMix: 0.84,
      seed: 229,
    }),
    createBurstEmitter('Delayed Ground Debris', {
      positionX: 0.5, positionY: 0.055, positionZ: 0.5,
      radius: 0.08,
      startTime: 0.42,
      duration: 0.28,
      densityAmount: 0.28,
      heatAmount: 0,
      fuelAmount: 0,
      reactionAmount: 0,
      expansionSpeed: 12,
      liftSpeed: 4,
      turbulenceSpeed: 18,
      falloff: 0.58,
      noiseScale: 18,
      noiseMix: 0.68,
      seed: 239,
    }),
    createVelocityEmitter('Crosswind Tear', {
      positionX: 0.5, positionY: 0.2, positionZ: 0.5,
      radius: 0.16,
      startTime: 0.2,
      duration: 2.8,
      mode: 'directional',
      speed: 12,
      directionX: 0.38, directionY: 0.12, directionZ: -0.18,
      falloff: 0.7,
      tightness: 0.08,
      seed: 251,
    }),
  ],
  lights: [
    createLight('Overcast Sky', {
      lightType: 'directional',
      dirX: -0.28, dirY: 0.92, dirZ: 0.26,
      posX: 0.5, posY: 0.85, posZ: 0.5,
      intensity: 1.85,
      colorR: 0.92, colorG: 0.94, colorB: 1.0,
    }),
  ],
  runtimeParams: {
    wind: [0.032, 0, -0.018],
    windStrength: 0.14,
    gravity: [0, -1, 0],
    gravityStrength: 0.48,
    buoyancy: 2.4,
    vorticityStrength: 5.6,
    vorticityConstantMask: 0.9,
    vorticityVelocityMask: 1.0,
    vorticityHeatMask: 0.7,
    vorticityDensityMask: 0.9,
    worldSize: 50,
  },
  renderOutput: {
    stepCount: 420,
    scatteringForward: 0.34,
    scatteringBack: -0.16,
  },
}
