import { createBurstEmitter, createScalarEmitter, createVelocityEmitter, createLight, type PresetEmitter, type NewFilePreset } from './types'

function impact(label: string, x: number, y: number, z: number, t: number, seed: number): PresetEmitter[] {
  return [
    createBurstEmitter(`${label} Blast`, {
      positionX: x, positionY: y, positionZ: z,
      radius: 0.06,
      startTime: t,
      duration: 0.12,
      densityAmount: 0.26,
      heatAmount: 0.95,
      fuelAmount: 0.18,
      reactionAmount: 0.42,
      expansionSpeed: 54,
      liftSpeed: 6,
      turbulenceSpeed: 24,
      falloff: 0.38,
      noiseScale: 20,
      noiseMix: 0.74,
      seed,
    }),
    createScalarEmitter(`${label} Lingering Dirt`, {
      positionX: x, positionY: y + 0.055, positionZ: z,
      radius: 0.06,
      startTime: t + 0.18,
      duration: 2.6,
      densityRate: 0.72,
      heatRate: 0.12,
      fuelRate: 0,
      noiseScale: 24,
      noiseMix: 0.82,
      seed: seed + 2,
    }),
    createVelocityEmitter(`${label} Low Roll`, {
      positionX: x, positionY: 0.055, positionZ: z,
      radius: 0.1,
      startTime: t + 0.1,
      duration: 1.4,
      mode: 'radial',
      speed: 12,
      directionX: 0, directionY: 0, directionZ: 0,
      falloff: 0.66,
      tightness: 0.12,
      seed: seed + 4,
    }),
  ]
}

export const artillerySalvoPreset: NewFilePreset = {
  id: 'artillery-salvo',
  label: 'Artillery Salvo',
  description: 'Four timed impacts with separate dirt plumes that shear together in wind.',
  emitters: [
    ...impact('Impact A', 0.34, 0.065, 0.56, 0, 1613),
    ...impact('Impact B', 0.62, 0.07, 0.48, 0.75, 1621),
    ...impact('Impact C', 0.46, 0.06, 0.63, 1.55, 1637),
    ...impact('Impact D', 0.55, 0.075, 0.38, 2.35, 1663),
    createScalarEmitter('Battlefield Haze Bed', {
      positionX: 0.5, positionY: 0.06, positionZ: 0.52,
      radius: 0.28,
      startTime: 0.35,
      duration: 5.8,
      densityRate: 0.48,
      heatRate: 0,
      fuelRate: 0,
      noiseScale: 14,
      noiseMix: 0.76,
      seed: 1669,
    }),
    createVelocityEmitter('Shared Wind Shear', {
      positionX: 0.5, positionY: 0.16, positionZ: 0.52,
      radius: 0.34,
      startTime: 0.4,
      duration: 6,
      mode: 'directional',
      speed: 10,
      directionX: 0.46, directionY: 0.2, directionZ: -0.18,
      falloff: 0.74,
      tightness: 0.06,
      seed: 1693,
    }),
  ],
  lights: [
    createLight('Battlefield Haze', {
      lightType: 'directional',
      dirX: -0.36, dirY: 0.86, dirZ: 0.28,
      posX: 0.5, posY: 0.82, posZ: 0.5,
      intensity: 1.5,
      colorR: 1.0, colorG: 0.93, colorB: 0.82,
    }),
  ],
  runtimeParams: {
    wind: [0.045, 0, -0.018],
    windStrength: 0.18,
    gravity: [0, -1, 0],
    gravityStrength: 0.48,
    buoyancy: 2.8,
    vorticityStrength: 5.8,
    vorticityConstantMask: 0.85,
    vorticityVelocityMask: 0.9,
    vorticityHeatMask: 0.55,
    vorticityDensityMask: 0.95,
    worldSize: 90,
  },
  renderOutput: {
    stepCount: 500,
    scatteringForward: 0.25,
    scatteringBack: -0.11,
  },
}
