import { createScalarEmitter, createVelocityEmitter, createIgniterEmitter, createLight, type NewFilePreset } from './types'

export const artillerySalvoPreset: NewFilePreset = {
  id: 'artillery-salvo',
  label: 'Artillery Salvo',
  description: 'Four separate impacts fired over time, leaving overlapping smoke and dust.',
  emitters: [
    createScalarEmitter('Impact A Flash', {
      positionX: 0.34, positionY: 0.065, positionZ: 0.56,
      radius: 0.055,
      startTime: 0,
      duration: 0.16,
      densityRate: 2.4,
      heatRate: 14,
      fuelRate: 3.8,
      noiseScale: 42,
      noiseMix: 0.86,
      seed: 1613,
    }),
    createVelocityEmitter('Impact A Blast', {
      positionX: 0.34, positionY: 0.065, positionZ: 0.56,
      radius: 0.075,
      startTime: 0,
      duration: 0.18,
      mode: 'radial',
      speed: 46,
      directionX: 0, directionY: 0, directionZ: 0,
      falloff: 0.38,
      seed: 1619,
    }),
    createScalarEmitter('Impact B Flash', {
      positionX: 0.62, positionY: 0.07, positionZ: 0.48,
      radius: 0.06,
      startTime: 0.75,
      duration: 0.16,
      densityRate: 2.7,
      heatRate: 15,
      fuelRate: 4.0,
      noiseScale: 46,
      noiseMix: 0.86,
      seed: 1621,
    }),
    createVelocityEmitter('Impact B Blast', {
      positionX: 0.62, positionY: 0.07, positionZ: 0.48,
      radius: 0.08,
      startTime: 0.75,
      duration: 0.18,
      mode: 'radial',
      speed: 52,
      directionX: 0, directionY: 0, directionZ: 0,
      falloff: 0.36,
      seed: 1627,
    }),
    createScalarEmitter('Impact C Flash', {
      positionX: 0.46, positionY: 0.06, positionZ: 0.63,
      radius: 0.052,
      startTime: 1.55,
      duration: 0.14,
      densityRate: 2.2,
      heatRate: 13,
      fuelRate: 3.2,
      noiseScale: 40,
      noiseMix: 0.84,
      seed: 1637,
    }),
    createVelocityEmitter('Impact C Blast', {
      positionX: 0.46, positionY: 0.06, positionZ: 0.63,
      radius: 0.072,
      startTime: 1.55,
      duration: 0.18,
      mode: 'radial',
      speed: 44,
      directionX: 0, directionY: 0, directionZ: 0,
      falloff: 0.4,
      seed: 1657,
    }),
    createScalarEmitter('Impact D Flash', {
      positionX: 0.55, positionY: 0.075, positionZ: 0.38,
      radius: 0.058,
      startTime: 2.35,
      duration: 0.15,
      densityRate: 2.5,
      heatRate: 14,
      fuelRate: 3.5,
      noiseScale: 44,
      noiseMix: 0.86,
      seed: 1663,
    }),
    createVelocityEmitter('Impact D Blast', {
      positionX: 0.55, positionY: 0.075, positionZ: 0.38,
      radius: 0.078,
      startTime: 2.35,
      duration: 0.18,
      mode: 'radial',
      speed: 48,
      directionX: 0, directionY: 0, directionZ: 0,
      falloff: 0.38,
      seed: 1667,
    }),
    createScalarEmitter('Shared Dust Field', {
      positionX: 0.5, positionY: 0.055, positionZ: 0.52,
      radius: 0.27,
      startTime: 0.25,
      duration: 6.2,
      densityRate: 1.55,
      heatRate: 0,
      fuelRate: 0,
      noiseScale: 18,
      noiseMix: 0.68,
      seed: 1669,
    }),
    createScalarEmitter('Hanging Impact Smoke', {
      positionX: 0.52, positionY: 0.16, positionZ: 0.52,
      radius: 0.24,
      startTime: 1.0,
      duration: 5.5,
      densityRate: 1.3,
      heatRate: 0.15,
      fuelRate: 0,
      noiseScale: 16,
      noiseMix: 0.76,
      seed: 1693,
    }),
    createIgniterEmitter('Impact A Ignition', {
      positionX: 0.34, positionY: 0.065, positionZ: 0.56,
      radius: 0.058,
      startTime: 0,
      duration: 0.1,
      intensity: 0.9,
      seed: 1697,
    }),
    createIgniterEmitter('Impact B Ignition', {
      positionX: 0.62, positionY: 0.07, positionZ: 0.48,
      radius: 0.062,
      startTime: 0.75,
      duration: 0.1,
      intensity: 0.9,
      seed: 1699,
    }),
  ],
  lights: [
    createLight('Battlefield Haze', {
      lightType: 'directional',
      dirX: -0.36, dirY: 0.86, dirZ: 0.28,
      posX: 0.5, posY: 0.82, posZ: 0.5,
      intensity: 1.5,
      colorR: 1.0, colorG: 0.93, colorB: 0.82,
    }),
  ],
  runtimeParams: {
    wind: [0.045, 0, -0.018],
    windStrength: 0.24,
    gravity: [0, -1, 0],
    gravityStrength: 0.45,
    buoyancy: 3.1,
    vorticityStrength: 5.0,
    worldSize: 90,
  },
  renderOutput: {
    stepCount: 470,
    scatteringForward: 0.25,
    scatteringBack: -0.11,
  },
}
