import { createBurstEmitter, createScalarEmitter, createVelocityEmitter, createLight, type PresetEmitter, type NewFilePreset } from './types'

// Artillery salvo: each impact needs (1) a fast explosive burst that pushes dirt OUT radially,
// (2) a rising dirt column from the center, and (3) the column must form BEFORE the simulation
// volume boundary is hit. Old preset had huge worldSize=90 with weak bursts — dirt escaped before
// developing. Fix: smaller world + stronger impulse + tighter column feed per impact.
// The "escaping the volume" issue = worldSize too large relative to burst energy.
function impact(label: string, x: number, y: number, z: number, t: number, seed: number): PresetEmitter[] {
  return [
    // Very short, hot burst — the actual detonation. Small radius, huge speed.
    createBurstEmitter(`${label} Detonation`, {
      positionX: x, positionY: y, positionZ: z,
      radius: 0.042,
      startTime: t,
      duration: 0.07,
      densityAmount: 0.18,
      heatAmount: 1.15,
      fuelAmount: 0.22,
      reactionAmount: 0.65,
      expansionSpeed: 110,
      liftSpeed: 22,
      turbulenceSpeed: 55,
      falloff: 0.26,
      noiseScale: 28,
      noiseMix: 0.84,
      seed,
    }),
    // Dirt ring pushed radially outward from the crater — stays low
    createVelocityEmitter(`${label} Crater Ring`, {
      positionX: x, positionY: y - 0.015, positionZ: z,
      radius: 0.085,
      startTime: t + 0.04,
      duration: 0.55,
      mode: 'radial',
      speed: 38,
      directionX: 0, directionY: 0, directionZ: 0,
      falloff: 0.54,
      tightness: 0.28,
      seed: seed + 1,
    }),
    // Tight rising dirt column — narrow, fast, vertical
    createScalarEmitter(`${label} Column Feed`, {
      positionX: x, positionY: y + 0.02, positionZ: z,
      radius: 0.016,
      startTime: t + 0.06,
      duration: 2.2,
      densityRate: 1.85,
      heatRate: 0.45,
      fuelRate: 0,
      noiseScale: 32,
      noiseMix: 0.88,
      seed: seed + 2,
    }),
    createVelocityEmitter(`${label} Column Jet`, {
      positionX: x, positionY: y + 0.02, positionZ: z,
      radius: 0.022,
      startTime: t + 0.06,
      duration: 2.4,
      mode: 'directional',
      speed: 44,
      directionX: 0.05, directionY: 1, directionZ: -0.03,
      falloff: 0.9,
      tightness: 0.58,
      seed: seed + 3,
    }),
  ]
}

export const artillerySalvoPreset: NewFilePreset = {
  id: 'artillery-salvo',
  label: 'Artillery Salvo',
  description: 'Four staggered impacts with crater rings and rising dirt columns shearing in wind.',
  emitters: [
    ...impact('Impact A', 0.33, 0.062, 0.57, 0, 1613),
    ...impact('Impact B', 0.61, 0.065, 0.46, 0.9, 1621),
    ...impact('Impact C', 0.44, 0.060, 0.64, 1.85, 1637),
    ...impact('Impact D', 0.56, 0.068, 0.37, 2.8, 1663),
    // Local dust hangers. Keep these small and brief; scalar duration compounds into total smoke mass.
    createBurstEmitter('Near-Crater Haze A', {
      positionX: 0.39, positionY: 0.052, positionZ: 0.59,
      radius: 0.085,
      startTime: 0.65,
      duration: 2.1,
      densityAmount: 0.12,
      heatAmount: 0,
      fuelAmount: 0,
      reactionAmount: 0,
      expansionSpeed: 0.9,
      liftSpeed: -0.05,
      turbulenceSpeed: 0.9,
      falloff: 0.86,
      noiseScale: 19,
      noiseMix: 0.78,
      seed: 1669,
    }),
    createBurstEmitter('Near-Crater Haze B', {
      positionX: 0.58, positionY: 0.055, positionZ: 0.43,
      radius: 0.075,
      startTime: 1.35,
      duration: 2.0,
      densityAmount: 0.105,
      heatAmount: 0,
      fuelAmount: 0,
      reactionAmount: 0,
      expansionSpeed: 0.85,
      liftSpeed: -0.04,
      turbulenceSpeed: 0.82,
      falloff: 0.88,
      noiseScale: 23,
      noiseMix: 0.82,
      seed: 1671,
    }),
    createBurstEmitter('Trailing Battlefield Dust', {
      positionX: 0.51, positionY: 0.057, positionZ: 0.51,
      radius: 0.095,
      startTime: 2.25,
      duration: 1.8,
      densityAmount: 0.1,
      heatAmount: 0,
      fuelAmount: 0,
      reactionAmount: 0,
      expansionSpeed: 0.72,
      liftSpeed: -0.04,
      turbulenceSpeed: 0.78,
      falloff: 0.88,
      noiseScale: 16,
      noiseMix: 0.86,
      seed: 1673,
    }),
    // Wind shear at medium height — bends the columns after they rise above the smoke bed
    createVelocityEmitter('Upper Wind Shear', {
      positionX: 0.5, positionY: 0.28, positionZ: 0.52,
      radius: 0.48,
      startTime: 0.2,
      duration: 9999,
      mode: 'directional',
      speed: 16,
      directionX: 0.58, directionY: 0.15, directionZ: -0.22,
      falloff: 0.82,
      tightness: 0.04,
      seed: 1693,
    }),
  ],
  lights: [
    createLight('Battlefield Overcast', {
      lightType: 'directional',
      dirX: -0.36, dirY: 0.86, dirZ: 0.28,
      posX: 0.5, posY: 0.82, posZ: 0.5,
      intensity: 1.4,
      colorR: 0.96, colorG: 0.90, colorB: 0.78,
    }),
  ],
  runtimeParams: {
    wind: [0.052, 0, -0.022],
    windStrength: 0.28,
    gravity: [0, -1, 0],
    gravityStrength: 0.5,
    buoyancy: 2.2,
    vorticityStrength: 3.5,
    vorticityConstantMask: 0.5,
    vorticityVelocityMask: 0.6,
    vorticityHeatMask: 0.3,
    vorticityDensityMask: 0.4,
    worldSize: 55,
  },
  renderOutput: {
    stepCount: 520,
    scatteringForward: 0.24,
    scatteringBack: -0.11,
  },
}
