import { createScalarEmitter, createVelocityEmitter, createIgniterEmitter, createLight, type NewFilePreset } from './types'

export const warehouseFirePreset: NewFilePreset = {
  id: 'warehouse-fire',
  label: 'Warehouse Fire',
  description: 'Multiple room-scale fire seats feeding a broad, dirty smoke layer.',
  emitters: [
    createScalarEmitter('Left Fire Seat', {
      positionX: 0.34, positionY: 0.06, positionZ: 0.52,
      radius: 0.05,
      startTime: 0,
      duration: 9999,
      densityRate: 0.4,
      heatRate: 7.2,
      fuelRate: 6.5,
      noiseScale: 9,
      noiseMix: 0.55,
      seed: 1319,
    }),
    createScalarEmitter('Center Fire Seat', {
      positionX: 0.49, positionY: 0.06, positionZ: 0.45,
      radius: 0.06,
      startTime: 1.2,
      duration: 9999,
      densityRate: 0.6,
      heatRate: 8.0,
      fuelRate: 7.5,
      noiseScale: 10,
      noiseMix: 0.6,
      seed: 1321,
    }),
    createScalarEmitter('Right Smoke Seat', {
      positionX: 0.65, positionY: 0.07, positionZ: 0.57,
      radius: 0.075,
      startTime: 2.4,
      duration: 9999,
      densityRate: 2.4,
      heatRate: 1.1,
      fuelRate: 1.2,
      noiseScale: 12,
      noiseMix: 0.65,
      seed: 1327,
    }),
    createScalarEmitter('Ceiling Smoke Layer', {
      positionX: 0.5, positionY: 0.22, positionZ: 0.52,
      radius: 0.16,
      startTime: 3.2,
      duration: 9999,
      densityRate: 1.6,
      heatRate: 0.2,
      fuelRate: 0,
      noiseScale: 8,
      noiseMix: 0.72,
      seed: 1361,
    }),
    createVelocityEmitter('Window Draft', {
      positionX: 0.38, positionY: 0.095, positionZ: 0.52,
      radius: 0.13,
      startTime: 0.4,
      duration: 9999,
      mode: 'directional',
      speed: 7.2,
      directionX: 0.3, directionY: 1, directionZ: -0.08,
      falloff: 0.88,
      tightness: 0.18,
      seed: 1367,
    }),
    createVelocityEmitter('Interior Churn', {
      positionX: 0.52, positionY: 0.16, positionZ: 0.52,
      radius: 0.24,
      startTime: 1.0,
      duration: 9999,
      mode: 'turbulent',
      speed: 3.2,
      directionX: 0, directionY: 1, directionZ: 0,
      falloff: 0.95,
      tightness: 0.08,
      seed: 1373,
    }),
    createIgniterEmitter('Initial Flame', {
      positionX: 0.34, positionY: 0.065, positionZ: 0.52,
      radius: 0.055,
      startTime: 0,
      duration: 0.35,
      intensity: 0.85,
      seed: 1381,
    }),
    createIgniterEmitter('Spread Ignition', {
      positionX: 0.49, positionY: 0.065, positionZ: 0.45,
      radius: 0.06,
      startTime: 1.2,
      duration: 0.35,
      intensity: 0.7,
      seed: 1399,
    }),
  ],
  lights: [
    createLight('Smoke-Dimmed Sun', {
      lightType: 'directional',
      dirX: -0.32, dirY: 0.88, dirZ: 0.24,
      posX: 0.5, posY: 0.82, posZ: 0.5,
      intensity: 1.35,
      colorR: 1.0, colorG: 0.88, colorB: 0.72,
    }),
  ],
  runtimeParams: {
    wind: [0.025, 0, -0.012],
    windStrength: 0.12,
    gravity: [0, -1, 0],
    gravityStrength: 0.45,
    buoyancy: 3.2,
    vorticityStrength: 4.8,
    vorticityConstantMask: 0.65,
    vorticityVelocityMask: 0.55,
    vorticityHeatMask: 1.0,
    vorticityDensityMask: 0.8,
    worldSize: 26,
  },
  renderOutput: {
    stepCount: 440,
    scatteringForward: 0.2,
    scatteringBack: -0.08,
  },
}
