import { createScalarEmitter, createVelocityEmitter, createIgniterEmitter, createLight, type NewFilePreset } from './types'

export const gasLineRupturePreset: NewFilePreset = {
  id: 'gas-line-rupture',
  label: 'Gas Line Rupture',
  description: 'Horizontal jet fire with a bright initial flash and wind-torn exhaust.',
  emitters: [
    createScalarEmitter('Rupture Flame Jet', {
      positionX: 0.38, positionY: 0.08, positionZ: 0.52,
      radius: 0.055,
      startTime: 0,
      duration: 9999,
      densityRate: 0.15,
      heatRate: 10.5,
      fuelRate: 10.8,
      noiseScale: 12,
      noiseMix: 0.45,
      seed: 1511,
    }),
    createVelocityEmitter('Lateral Jet Momentum', {
      positionX: 0.38, positionY: 0.08, positionZ: 0.52,
      radius: 0.07,
      startTime: 0,
      duration: 9999,
      mode: 'directional',
      speed: 20,
      directionX: 1, directionY: 0.22, directionZ: -0.08,
      falloff: 0.68,
      seed: 1523,
    }),
    createScalarEmitter('Lifted Soot Trail', {
      positionX: 0.55, positionY: 0.13, positionZ: 0.49,
      radius: 0.095,
      startTime: 0.9,
      duration: 9999,
      densityRate: 1.9,
      heatRate: 0.35,
      fuelRate: 0,
      noiseScale: 18,
      noiseMix: 0.74,
      seed: 1531,
    }),
    createVelocityEmitter('Trail Breakup', {
      positionX: 0.58, positionY: 0.14, positionZ: 0.48,
      radius: 0.16,
      startTime: 0.6,
      duration: 9999,
      mode: 'turbulent',
      speed: 4.0,
      directionX: 0, directionY: 1, directionZ: 0,
      falloff: 0.95,
      seed: 1543,
    }),
    createIgniterEmitter('Flash Ignition', {
      positionX: 0.38, positionY: 0.08, positionZ: 0.52,
      radius: 0.075,
      startTime: 0,
      duration: 0.18,
      intensity: 1.0,
      seed: 1553,
    }),
  ],
  lights: [
    createLight('Hard Sun', {
      lightType: 'directional',
      dirX: -0.2, dirY: 0.95, dirZ: 0.18,
      posX: 0.5, posY: 0.88, posZ: 0.5,
      intensity: 2.2,
      colorR: 1.0, colorG: 0.96, colorB: 0.9,
    }),
  ],
  runtimeParams: {
    wind: [0.06, 0, -0.02],
    windStrength: 0.34,
    gravity: [0, -1, 0],
    gravityStrength: 0.45,
    buoyancy: 3.8,
    vorticityStrength: 3.6,
    worldSize: 30,
  },
  renderOutput: {
    stepCount: 410,
    scatteringForward: 0.2,
    scatteringBack: -0.07,
  },
}
