import { createScalarEmitter, createVelocityEmitter, createIgniterEmitter, createLight, type NewFilePreset } from './types'

export const fuelTankExplosionPreset: NewFilePreset = {
  id: 'fuel-tank-explosion',
  label: 'Fuel Tank Explosion',
  description: 'Large hydrocarbon fireball with a delayed black column and ground dust.',
  emitters: [
    createScalarEmitter('Vapor Cloud Flash', {
      positionX: 0.5, positionY: 0.1, positionZ: 0.5,
      radius: 0.105,
      startTime: 0,
      duration: 0.28,
      densityRate: 2.2,
      heatRate: 17,
      fuelRate: 15,
      noiseScale: 46,
      noiseMix: 0.85,
      seed: 1411,
    }),
    createVelocityEmitter('Tank Rupture Push', {
      positionX: 0.5, positionY: 0.095, positionZ: 0.5,
      radius: 0.12,
      startTime: 0,
      duration: 0.2,
      mode: 'radial',
      speed: 70,
      directionX: 0, directionY: 0, directionZ: 0,
      falloff: 0.32,
      seed: 1423,
    }),
    createScalarEmitter('Rolling Fireball Smoke', {
      positionX: 0.52, positionY: 0.18, positionZ: 0.49,
      radius: 0.12,
      startTime: 0.45,
      duration: 2.2,
      densityRate: 2.5,
      heatRate: 2.4,
      fuelRate: 1.2,
      noiseScale: 30,
      noiseMix: 0.78,
      seed: 1439,
    }),
    createVelocityEmitter('Fireball Lift', {
      positionX: 0.51, positionY: 0.145, positionZ: 0.49,
      radius: 0.13,
      startTime: 0.22,
      duration: 2.6,
      mode: 'directional',
      speed: 15,
      directionX: 0.1, directionY: 1, directionZ: -0.04,
      falloff: 0.76,
      seed: 1447,
    }),
    createScalarEmitter('Black Soot Column', {
      positionX: 0.55, positionY: 0.24, positionZ: 0.47,
      radius: 0.115,
      startTime: 1.6,
      duration: 5.4,
      densityRate: 2.8,
      heatRate: 0.25,
      fuelRate: 0,
      noiseScale: 24,
      noiseMix: 0.75,
      seed: 1451,
    }),
    createScalarEmitter('Ground Dust Ring', {
      positionX: 0.5, positionY: 0.052, positionZ: 0.5,
      radius: 0.18,
      startTime: 0.24,
      duration: 3.0,
      densityRate: 1.35,
      heatRate: 0,
      fuelRate: 0,
      noiseScale: 22,
      noiseMix: 0.64,
      seed: 1459,
    }),
    createVelocityEmitter('Dust Rollout', {
      positionX: 0.5, positionY: 0.052, positionZ: 0.5,
      radius: 0.2,
      startTime: 0.2,
      duration: 0.75,
      mode: 'radial',
      speed: 22,
      directionX: 0, directionY: 0, directionZ: 0,
      falloff: 0.5,
      seed: 1471,
    }),
    createIgniterEmitter('Vapor Ignition', {
      positionX: 0.5, positionY: 0.1, positionZ: 0.5,
      radius: 0.11,
      startTime: 0,
      duration: 0.12,
      intensity: 1.0,
      seed: 1481,
    }),
  ],
  lights: [
    createLight('Industrial Yard Sun', {
      lightType: 'directional',
      dirX: -0.26, dirY: 0.93, dirZ: 0.24,
      posX: 0.5, posY: 0.86, posZ: 0.5,
      intensity: 2.1,
      colorR: 1.0, colorG: 0.95, colorB: 0.86,
    }),
  ],
  runtimeParams: {
    wind: [0.05, 0, -0.022],
    windStrength: 0.24,
    gravity: [0, -1, 0],
    gravityStrength: 0.45,
    buoyancy: 4.9,
    vorticityStrength: 4.8,
    worldSize: 80,
  },
  renderOutput: {
    stepCount: 460,
    scatteringForward: 0.22,
    scatteringBack: -0.09,
  },
}
