import { createBurstEmitter, createScalarEmitter, createVelocityEmitter, createIgniterEmitter, createLight, type NewFilePreset } from './types'

// Nuclear detonation: source chains bind ignition/velocity to material emitters,
// while delayed cap force fields shape the rising column without spawning smoke in mid-air.
export const nuclearDetonationPreset: NewFilePreset = {
  id: 'nuclear-detonation',
  label: 'Nuclear Detonation',
  description: 'Ground flash, towering stem, broad shoulder, and a cauliflower mushroom cap.',
  emitters: [
    createBurstEmitter('White Hot Fireball', {
      positionX: 0.5, positionY: 0.065, positionZ: 0.5,
      radius: 0.075,
      startTime: 0,
      duration: 0.24,
      densityAmount: 0.34,
      heatAmount: 0.92,
      fuelAmount: 0.68,
      reactionAmount: 1.0,
      expansionSpeed: 13,
      liftSpeed: 6,
      turbulenceSpeed: 2.0,
      falloff: 0.42,
      noiseScale: 9,
      noiseMix: 0.22,
      seed: 3101,
    }),
    createIgniterEmitter('Core Ignition', {
      positionX: 0.5, positionY: 0.065, positionZ: 0.5,
      radius: 0.09,
      startTime: 0,
      duration: 0.28,
      intensity: 1.0,
      seed: 3103,
    }),
    createBurstEmitter('Ground Shock Dust', {
      positionX: 0.5, positionY: 0.04, positionZ: 0.5,
      radius: 0.17,
      startTime: 0.1,
      duration: 0.42,
      densityAmount: 0.46,
      heatAmount: 0.035,
      fuelAmount: 0,
      reactionAmount: 0,
      expansionSpeed: 5.2,
      liftSpeed: -0.28,
      turbulenceSpeed: 1.25,
      falloff: 0.82,
      noiseScale: 34,
      noiseMix: 0.86,
      seed: 3107,
    }),
    createBurstEmitter('Ground Haze Ring', {
      positionX: 0.5, positionY: 0.045, positionZ: 0.5,
      radius: 0.135,
      startTime: 0.08,
      duration: 1.8,
      densityAmount: 0.18,
      heatAmount: 0.018,
      fuelAmount: 0,
      reactionAmount: 0,
      expansionSpeed: 1.15,
      liftSpeed: -0.08,
      turbulenceSpeed: 0.72,
      falloff: 0.88,
      noiseScale: 62,
      noiseMix: 0.94,
      seed: 3109,
    }),
    createScalarEmitter('Rising Stem Core', {
      positionX: 0.5, positionY: 0.08, positionZ: 0.5,
      radius: 0.058,
      startTime: 0.08,
      duration: 10.2,
      densityRate: 4.8,
      heatRate: 1.62,
      fuelRate: 0.22,
      noiseScale: 38,
      noiseMix: 0.82,
      seed: 3111,
    }),
    createScalarEmitter('Dense Stem Soot', {
      positionX: 0.5, positionY: 0.105, positionZ: 0.5,
      radius: 0.084,
      startTime: 0.45,
      duration: 10.4,
      densityRate: 3.55,
      heatRate: 0.38,
      fuelRate: 0,
      noiseScale: 56,
      noiseMix: 0.9,
      seed: 3112,
    }),
    createScalarEmitter('Stem Billow Feed', {
      positionX: 0.5, positionY: 0.16, positionZ: 0.5,
      radius: 0.072,
      startTime: 1.15,
      duration: 6.2,
      densityRate: 1.65,
      heatRate: 0.22,
      fuelRate: 0,
      noiseScale: 72,
      noiseMix: 0.94,
      seed: 3114,
    }),
    createVelocityEmitter('Rising Stem Jet', {
      positionX: 0.5, positionY: 0.08, positionZ: 0.5,
      radius: 0.068,
      startTime: 0.06,
      duration: 9.0,
      mode: 'directional',
      speed: 11.4,
      directionX: 0.015, directionY: 1, directionZ: -0.01,
      falloff: 0.76,
      tightness: 0.38,
      seed: 3113,
    }),
    createVelocityEmitter('Stem Surface Breakup', {
      positionX: 0.5, positionY: 0.21, positionZ: 0.5,
      radius: 0.13,
      startTime: 1.1,
      duration: 8.5,
      mode: 'turbulent',
      speed: 3.1,
      directionX: 0, directionY: 1, directionZ: 0,
      falloff: 0.88,
      tightness: 0.022,
      seed: 3117,
    }),
    createVelocityEmitter('Shoulder Roll Out', {
      positionX: 0.5, positionY: 0.47, positionZ: 0.5,
      radius: 0.19,
      startTime: 2.35,
      duration: 7.2,
      mode: 'radial',
      speed: 3.95,
      directionX: 0, directionY: 0, directionZ: 0,
      falloff: 0.74,
      tightness: 0.12,
      seed: 3123,
    }),
    createVelocityEmitter('Cap Updraft Stall', {
      positionX: 0.5, positionY: 0.61, positionZ: 0.5,
      radius: 0.2,
      startTime: 3.0,
      duration: 5.8,
      mode: 'directional',
      speed: 2.4,
      directionX: 0, directionY: 1, directionZ: 0,
      falloff: 0.72,
      tightness: 0.18,
      seed: 3131,
    }),
    createVelocityEmitter('Cap Lateral Spread', {
      positionX: 0.5, positionY: 0.65, positionZ: 0.5,
      radius: 0.36,
      startTime: 3.3,
      duration: 7.2,
      mode: 'radial',
      speed: 4.05,
      directionX: 0, directionY: 0, directionZ: 0,
      falloff: 0.8,
      tightness: 0.08,
      seed: 3137,
    }),
    createVelocityEmitter('Cap Surface Lumps', {
      positionX: 0.5, positionY: 0.65, positionZ: 0.5,
      radius: 0.36,
      startTime: 3.1,
      duration: 7.4,
      mode: 'turbulent',
      speed: 3.15,
      directionX: 0, directionY: 0, directionZ: 0,
      falloff: 0.86,
      tightness: 0.018,
      seed: 3141,
    }),
  ],
  graphEdges: [
    { source: 0, target: 1 },
    { source: 1, target: 'combustion' },
    { source: 2, target: 'combustion' },
    { source: 3, target: 'combustion' },
    { source: 4, target: 5 },
    { source: 5, target: 6 },
    { source: 6, target: 'combustion' },
    { source: 7, target: 'combustion' },
    { source: 8, target: 'combustion' },
    { source: 9, target: 'combustion' },
    { source: 10, target: 'combustion' },
    { source: 11, target: 'combustion' },
  ],
  lights: [
    createLight('Blast Flash', {
      lightType: 'directional',
      dirX: -0.08, dirY: 1, dirZ: 0.04,
      posX: 0.5, posY: 0.5, posZ: 0.5,
      intensity: 5.2,
      colorR: 1.0, colorG: 0.95, colorB: 0.78,
    }),
  ],
  runtimeParams: {
    wind: [0.004, 0, -0.002],
    windStrength: 0.03,
    gravity: [0, -1, 0],
    gravityStrength: 0.32,
    buoyancy: 6.35,
    vorticityStrength: 2.75,
    vorticityConstantMask: 0.2,
    vorticityVelocityMask: 0.32,
    vorticityHeatMask: 0.48,
    vorticityDensityMask: 0.66,
    worldSize: 430,
  },
  renderOutput: {
    stepCount: 640,
    scatteringForward: 0.2,
    scatteringBack: -0.08,
    bloomEnabled: true,
    bloomThreshold: 0.58,
    bloomStrength: 0.52,
    bloomRadius: 0.7,
  },
}
