import { createScalarEmitter, createVelocityEmitter, createLight, type NewFilePreset } from './types'

export const demolitionDustPreset: NewFilePreset = {
  id: 'demolition-dust',
  label: 'Demolition Dust',
  description: 'Sequential collapse puffs expanding into a heavy low dust cloud.',
  emitters: [
    createScalarEmitter('First Floor Collapse', {
      positionX: 0.44, positionY: 0.06, positionZ: 0.52,
      radius: 0.1,
      startTime: 0,
      duration: 1.8,
      densityRate: 2.1,
      heatRate: 0,
      fuelRate: 0,
      noiseScale: 14,
      noiseMix: 0.68,
      seed: 1711,
    }),
    createVelocityEmitter('First Dust Push', {
      positionX: 0.44, positionY: 0.06, positionZ: 0.52,
      radius: 0.13,
      startTime: 0,
      duration: 0.8,
      mode: 'radial',
      speed: 12,
      directionX: 0, directionY: 0, directionZ: 0,
      falloff: 0.55,
      seed: 1721,
    }),
    createScalarEmitter('Second Collapse', {
      positionX: 0.57, positionY: 0.075, positionZ: 0.47,
      radius: 0.13,
      startTime: 1.2,
      duration: 2.6,
      densityRate: 2.7,
      heatRate: 0,
      fuelRate: 0,
      noiseScale: 12,
      noiseMix: 0.7,
      seed: 1733,
    }),
    createVelocityEmitter('Second Dust Push', {
      positionX: 0.57, positionY: 0.075, positionZ: 0.47,
      radius: 0.16,
      startTime: 1.2,
      duration: 1.1,
      mode: 'radial',
      speed: 15,
      directionX: 0, directionY: 0, directionZ: 0,
      falloff: 0.58,
      seed: 1741,
    }),
    createScalarEmitter('Street-Level Dust', {
      positionX: 0.52, positionY: 0.052, positionZ: 0.5,
      radius: 0.25,
      startTime: 2.2,
      duration: 7.0,
      densityRate: 1.55,
      heatRate: 0,
      fuelRate: 0,
      noiseScale: 10,
      noiseMix: 0.72,
      seed: 1747,
    }),
    createVelocityEmitter('Slow Collapse Boil', {
      positionX: 0.52, positionY: 0.12, positionZ: 0.5,
      radius: 0.27,
      startTime: 2.0,
      duration: 9999,
      mode: 'turbulent',
      speed: 2.4,
      directionX: 0, directionY: 1, directionZ: 0,
      falloff: 0.95,
      seed: 1753,
    }),
  ],
  lights: [
    createLight('Dusty Sun', {
      lightType: 'directional',
      dirX: -0.42, dirY: 0.82, dirZ: 0.28,
      posX: 0.5, posY: 0.8, posZ: 0.5,
      intensity: 1.6,
      colorR: 1.0, colorG: 0.92, colorB: 0.78,
    }),
  ],
  runtimeParams: {
    wind: [0.035, 0, -0.012],
    windStrength: 0.14,
    gravity: [0, -1, 0],
    gravityStrength: 0.58,
    buoyancy: 0.55,
    vorticityStrength: 2.7,
    worldSize: 60,
  },
  renderOutput: {
    displayMode: 'density',
    stepCount: 430,
    scatteringForward: 0.24,
    scatteringBack: -0.09,
  },
}
