import { createScalarEmitter, createVelocityEmitter, createLight, type NewFilePreset } from './types'

// Industrial smokestacks: the "three blobs" problem comes from slow upward velocity and
// low noise. Real stack plumes are COLUMN-shaped — narrow at the base, spreading and
// bending in the wind above. Fix: tight collocated velocity+scalar at the source,
// strong enough to form a column before lateral wind bends it. Stagger heights and
// rates for variety. Add strong horizontal wind shear that kicks in above the stacks.
export const industrialSmokestacksPreset: NewFilePreset = {
  id: 'industrial-smokestacks',
  label: 'Industrial Smokestacks',
  description: 'Three staggered stack plumes rising as tight columns before bending in upper wind.',
  emitters: [
    // Stack A — tallest, heaviest. heatRate kept very low — industrial exhaust is warm, not burning.
    // Anything above ~0.08 heatRate will trigger combustion glow near the source.
    createScalarEmitter('Stack A Smoke', {
      positionX: 0.3, positionY: 0.09, positionZ: 0.55,
      radius: 0.042,
      startTime: 0,
      duration: 9999,
      densityRate: 2.75,
      heatRate: 0.055,
      fuelRate: 0,
      noiseScale: 46,
      noiseMix: 0.94,
      seed: 1111,
    }),
    createVelocityEmitter('Stack A Jet', {
      positionX: 0.3, positionY: 0.09, positionZ: 0.55,
      radius: 0.052,
      startTime: 0,
      duration: 9999,
      mode: 'directional',
      speed: 21,
      directionX: 0.025, directionY: 1, directionZ: -0.015,
      falloff: 0.82,
      tightness: 0.48,
      seed: 1119,
    }),
    // Stack B
    createScalarEmitter('Stack B Smoke', {
      positionX: 0.5, positionY: 0.09, positionZ: 0.46,
      radius: 0.038,
      startTime: 0.6,
      duration: 9999,
      densityRate: 2.35,
      heatRate: 0.052,
      fuelRate: 0,
      noiseScale: 48,
      noiseMix: 0.95,
      seed: 1123,
    }),
    createVelocityEmitter('Stack B Jet', {
      positionX: 0.5, positionY: 0.09, positionZ: 0.46,
      radius: 0.047,
      startTime: 0.6,
      duration: 9999,
      mode: 'directional',
      speed: 19,
      directionX: 0.035, directionY: 1, directionZ: -0.02,
      falloff: 0.83,
      tightness: 0.46,
      seed: 1129,
    }),
    // Stack C — smaller
    createScalarEmitter('Stack C Smoke', {
      positionX: 0.68, positionY: 0.09, positionZ: 0.58,
      radius: 0.034,
      startTime: 1.2,
      duration: 9999,
      densityRate: 1.8,
      heatRate: 0.045,
      fuelRate: 0,
      noiseScale: 50,
      noiseMix: 0.95,
      seed: 1137,
    }),
    createVelocityEmitter('Stack C Jet', {
      positionX: 0.68, positionY: 0.09, positionZ: 0.58,
      radius: 0.043,
      startTime: 1.2,
      duration: 9999,
      mode: 'directional',
      speed: 16,
      directionX: 0.03, directionY: 1, directionZ: -0.012,
      falloff: 0.84,
      tightness: 0.44,
      seed: 1143,
    }),
    // Upper cross-wind bends the columns after they clear the stack tops
    createVelocityEmitter('Upper Crosswind', {
      positionX: 0.5, positionY: 0.38, positionZ: 0.5,
      radius: 0.48,
      startTime: 0.4,
      duration: 9999,
      mode: 'directional',
      speed: 10,
      directionX: 0.82, directionY: 0.04, directionZ: -0.22,
      falloff: 0.88,
      tightness: 0.04,
      seed: 1151,
    }),
    // Column turbulence
    createVelocityEmitter('Column Shear', {
      positionX: 0.48, positionY: 0.22, positionZ: 0.52,
      radius: 0.38,
      startTime: 0.8,
      duration: 9999,
      mode: 'turbulent',
      speed: 7.5,
      directionX: 0, directionY: 1, directionZ: 0,
      falloff: 0.9,
      tightness: 0.035,
      seed: 1163,
    }),
  ],
  graphEdges: [
    { source: 0, target: 1 },
    { source: 1, target: 'combustion' },
    { source: 2, target: 3 },
    { source: 3, target: 'combustion' },
    { source: 4, target: 5 },
    { source: 5, target: 'combustion' },
    { source: 6, target: 'combustion' },
    { source: 7, target: 'combustion' },
  ],
  lights: [
    createLight('Industrial Haze Sun', {
      lightType: 'directional',
      dirX: -0.55, dirY: 0.72, dirZ: 0.38,
      posX: 0.5, posY: 0.8, posZ: 0.5,
      intensity: 1.45,
      colorR: 1.0, colorG: 0.88, colorB: 0.72,
    }),
  ],
  runtimeParams: {
    wind: [0.055, 0, -0.015],
    windStrength: 0.35,
    gravity: [0, -1, 0],
    gravityStrength: 0.42,
    buoyancy: 1.25,
    vorticityStrength: 3.0,
    vorticityConstantMask: 0.5,
    vorticityVelocityMask: 0.62,
    vorticityHeatMask: 0.0,
    vorticityDensityMask: 0.82,
    worldSize: 30,
  },
  renderOutput: {
    displayMode: 'density',
    stepCount: 460,
    scatteringForward: 0.22,
    scatteringBack: -0.1,
  },
}
